image: node:22

pipelines:
  custom:
    deploy-frontend:
      - step:
          name: Deploy Frontend
          script:
            - echo "Frontend Deployment Started"
            - ssh -v ubuntu@34.14.157.13 '
                cd /home/ubuntu/helpdesk/frontend &&
                node -v &&
                git checkout dev &&
                git pull &&
                npm ci &&
                npm run build &&
                pm2 restart helpdesk-frontend:3001 &&
                echo "Frontend deployed successfully!"
              '

    deploy-backend:
      - step:
          name: Deploy Backend
          script:
            - echo "Backend Deployment Started"
            - ssh -v ubuntu@34.14.157.13 '
                cd /home/ubuntu/helpdesk/backend &&
                node -v &&
                git checkout dev &&
                git pull &&
                npm ci &&
                npm run build &&
                pm2 restart helpdesk-backend:3003 &&
                echo "Backend deployed successfully!"
              '
