/**
 * Widget Catalog
 *
 * Static seed data for WidgetDefinition collection.
 * Auto-inserted on first GET /api/v1/admin/widget-definitions call
 * if the collection is empty.
 */

export const WIDGET_CATALOG = [
  // ─── Ticketing ────────────────────────────────────────────────────────────

  {
    widgetKey: "ticket_open_count",
    module: "ticketing",
    displayName: "Open Tickets",
    description:
      "Current count of open (non-closed) tickets with trend vs previous period.",
    supportedVisualisations: ["kpi_tile", "sparkline"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "project", "centre", "user"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ticket_open_count",
    defaultConfig: { dateRangeDays: 30 },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_closed_count",
    module: "ticketing",
    displayName: "Closed Tickets",
    description: "Count of tickets closed in the selected date range.",
    supportedVisualisations: ["kpi_tile", "sparkline"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "project", "centre", "user"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ticket_closed_count",
    defaultConfig: { dateRangeDays: 30 },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_by_status",
    module: "ticketing",
    displayName: "Tickets by Status",
    description: "Breakdown of all tickets grouped by current status.",
    supportedVisualisations: ["donut_chart", "bar_chart", "table"],
    defaultVisualisation: "donut_chart",
    scopeLevels: ["tenant", "project", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ticket_by_status",
    defaultConfig: { dateRangeDays: 30 },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_sla_resolution_rate",
    module: "ticketing",
    displayName: "SLA Resolution Rate",
    description: "Percentage of tickets resolved within SLA target time.",
    supportedVisualisations: ["gauge", "progress_bar", "kpi_tile"],
    defaultVisualisation: "gauge",
    scopeLevels: ["tenant", "project", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_sla_resolution_rate",
    defaultConfig: { dateRangeDays: 30 },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_sla_compliance",
    module: "ticketing",
    displayName: "SLA Compliance",
    description:
      "Overall SLA compliance rate across all open and closed tickets.",
    supportedVisualisations: ["gauge", "progress_bar", "kpi_tile"],
    defaultVisualisation: "gauge",
    scopeLevels: ["tenant", "project", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_sla_compliance",
    defaultConfig: { dateRangeDays: 30 },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_trend_over_time",
    module: "ticketing",
    displayName: "Ticket Trend",
    description:
      "Daily ticket creation and closure trend over the selected period.",
    supportedVisualisations: ["line_chart", "bar_chart", "area_chart"],
    defaultVisualisation: "line_chart",
    scopeLevels: ["tenant", "project", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_trend_over_time",
    defaultConfig: { dateRangeDays: 30 },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_assignee_workload",
    module: "ticketing",
    displayName: "Agent Workload",
    description: "Open ticket count per assigned agent.",
    supportedVisualisations: ["bar_chart", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant", "project", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ticket_assignee_workload",
    defaultConfig: { dateRangeDays: 30 },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "my_assigned_tickets",
    module: "ticketing",
    displayName: "My Assigned Tickets",
    description: "Tickets assigned to the currently logged-in user.",
    supportedVisualisations: ["kpi_tile", "table"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["user"],
    cacheTtlSeconds: 60,
    dataQueryKey: "my_assigned_tickets",
    defaultConfig: {
      dateRangeDays: 30,
      filters: { assignedTo: "@ctx.userId" },
    },
    isActive: true,
    version: 1,
  },

  // ─── Onboarding ───────────────────────────────────────────────────────────

  {
    widgetKey: "user_required_vs_onboarded",
    module: "onboarding",
    displayName: "Required vs Onboarded Users",
    description:
      "Comparison of target user count vs actually onboarded users per centre/project.",
    supportedVisualisations: ["bar_chart", "grouped_bar", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant", "project", "centre"],
    cacheTtlSeconds: 600,
    dataQueryKey: "user_required_vs_onboarded",
    defaultConfig: { dateRangeDays: 30 },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "user_active_count",
    module: "onboarding",
    displayName: "Active Users",
    description: "Count of currently active users in the system.",
    supportedVisualisations: ["kpi_tile", "sparkline"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "project", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "user_active_count",
    defaultConfig: {},
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "user_inactive_count",
    module: "onboarding",
    displayName: "Inactive Users",
    description: "Count of currently inactive/deactivated users.",
    supportedVisualisations: ["kpi_tile", "sparkline"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "project", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "user_inactive_count",
    defaultConfig: {},
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "user_onboarding_completion_rate",
    module: "onboarding",
    displayName: "Onboarding Completion Rate",
    description: "Percentage of target users who have been onboarded.",
    supportedVisualisations: ["gauge", "progress_bar", "kpi_tile"],
    defaultVisualisation: "gauge",
    scopeLevels: ["tenant", "project", "centre"],
    cacheTtlSeconds: 600,
    dataQueryKey: "user_onboarding_completion_rate",
    defaultConfig: { dateRangeDays: 30 },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "user_by_role",
    module: "onboarding",
    displayName: "Users by Role",
    description: "Distribution of active users across different roles.",
    supportedVisualisations: ["donut_chart", "bar_chart", "table"],
    defaultVisualisation: "donut_chart",
    scopeLevels: ["tenant", "project", "centre"],
    cacheTtlSeconds: 600,
    dataQueryKey: "user_by_role",
    defaultConfig: {},
    isActive: true,
    version: 1,
  },

  // ─── Capacity ─────────────────────────────────────────────────────────────

  {
    widgetKey: "centre_ideal_vs_active",
    module: "capacity",
    displayName: "Ideal vs Active Staff per Centre",
    description:
      "Comparison of ideal headcount target vs current active staff per centre.",
    supportedVisualisations: ["bar_chart", "grouped_bar", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant", "project"],
    cacheTtlSeconds: 600,
    dataQueryKey: "centre_ideal_vs_active",
    defaultConfig: {},
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "centre_capacity_gap",
    module: "capacity",
    displayName: "Centre Capacity Gap",
    description: "Gap between ideal and active staff count per centre.",
    supportedVisualisations: ["bar_chart", "table", "kpi_tile"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant", "project"],
    cacheTtlSeconds: 600,
    dataQueryKey: "centre_capacity_gap",
    defaultConfig: {},
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "centre_capacity_utilisation",
    module: "capacity",
    displayName: "Centre Capacity Utilisation",
    description: "Percentage of ideal capacity that is currently filled.",
    supportedVisualisations: ["gauge", "progress_bar", "bar_chart"],
    defaultVisualisation: "gauge",
    scopeLevels: ["tenant", "project"],
    cacheTtlSeconds: 600,
    dataQueryKey: "centre_capacity_utilisation",
    defaultConfig: {},
    isActive: true,
    version: 1,
  },

  // ─── Attendance ───────────────────────────────────────────────────────────

  {
    widgetKey: "attendance_today_rate",
    module: "attendance",
    displayName: "Today's Attendance Rate",
    description: "Attendance percentage for today across the project.",
    supportedVisualisations: ["kpi_tile", "gauge", "progress_bar"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "project", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "attendance_today_rate",
    defaultConfig: {},
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "attendance_mtd_rate",
    module: "attendance",
    displayName: "Month-to-Date Attendance Rate",
    description: "Average attendance rate for the current month.",
    supportedVisualisations: ["gauge", "progress_bar", "kpi_tile"],
    defaultVisualisation: "gauge",
    scopeLevels: ["tenant", "project", "centre"],
    cacheTtlSeconds: 600,
    dataQueryKey: "attendance_mtd_rate",
    defaultConfig: {},
    isActive: true,
    version: 1,
  },
];
