/**
 * Permission Code Constants
 * Keep this in sync with backend/src/utils/seedRolesPermissions.ts
 */

export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  DASHBOARD_VIEW_ANALYTICS: "DASHBOARD_VIEW_ANALYTICS",
  DASHBOARD_EXPORT: "DASHBOARD_EXPORT",

  // Hierarchical Dashboard (Team Views)
  DASHBOARD_VIEW_OWN: "DASHBOARD_VIEW_OWN",
  DASHBOARD_VIEW_TEAM: "DASHBOARD_VIEW_TEAM",
  DASHBOARD_VIEW_HIERARCHY: "DASHBOARD_VIEW_HIERARCHY",
  DASHBOARD_VIEW_TEAM_BREAKDOWN: "DASHBOARD_VIEW_TEAM_BREAKDOWN",
  DASHBOARD_VIEW_ALL: "DASHBOARD_VIEW_ALL",

  // Hierarchy Management
  HIERARCHY_MANAGE_TEAM: "HIERARCHY_MANAGE_TEAM",
  HIERARCHY_VIEW_TEAM: "HIERARCHY_VIEW_TEAM",

  // Project Management
  PROJECT_VIEW_ALL: "PROJECT_VIEW_ALL",
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_EDIT: "PROJECT_EDIT",
  PROJECT_DELETE: "PROJECT_DELETE",
  PROJECT_TOGGLE_STATUS: "PROJECT_TOGGLE_STATUS",
  PROJECT_MANAGE_SETTINGS: "PROJECT_MANAGE_SETTINGS",
  PROJECT_MANAGE_BRANDING: "PROJECT_MANAGE_BRANDING",
  PROJECT_MANAGE_URL: "PROJECT_MANAGE_URL",
  PROJECT_ASSIGN_USERS: "PROJECT_ASSIGN_USERS",

  // Master Data
  MASTER_DATA_VIEW: "MASTER_DATA_VIEW",
  MASTER_DATA_MANAGE: "MASTER_DATA_MANAGE",
  MASTER_DATA_CREATE: "MASTER_DATA_CREATE",
  MASTER_DATA_EDIT: "MASTER_DATA_EDIT",
  MASTER_DATA_DELETE: "MASTER_DATA_DELETE",
  MASTER_DATA_MANAGE_CATEGORIES: "MASTER_DATA_MANAGE_CATEGORIES",
  MASTER_DATA_MANAGE_PRIORITIES: "MASTER_DATA_MANAGE_PRIORITIES",
  MASTER_DATA_MANAGE_STATUSES: "MASTER_DATA_MANAGE_STATUSES",
  MASTER_DATA_MANAGE_DEPARTMENTS: "MASTER_DATA_MANAGE_DEPARTMENTS",
  MASTER_DATA_MANAGE_LOCATIONS: "MASTER_DATA_MANAGE_LOCATIONS",
  MASTER_DATA_MANAGE_COUNTRIES: "MASTER_DATA_MANAGE_COUNTRIES",
  MASTER_DATA_MANAGE_STATES: "MASTER_DATA_MANAGE_STATES",
  MASTER_DATA_MANAGE_CITIES: "MASTER_DATA_MANAGE_CITIES",
  MASTER_DATA_MANAGE_ASSET_CATEGORIES: "MASTER_DATA_MANAGE_ASSET_CATEGORIES",

  // RBAC Setup
  RBAC_VIEW_ROLES: "RBAC_VIEW_ROLES",
  RBAC_CREATE_ROLE: "RBAC_CREATE_ROLE",
  RBAC_EDIT_ROLE: "RBAC_EDIT_ROLE",
  RBAC_DELETE_ROLE: "RBAC_DELETE_ROLE",
  RBAC_ASSIGN_PERMISSIONS: "RBAC_ASSIGN_PERMISSIONS",
  RBAC_VIEW_PERMISSIONS: "RBAC_VIEW_PERMISSIONS",

  // User Management
  USER_VIEW_ALL: "USER_VIEW_ALL",
  USER_CREATE: "USER_CREATE",
  USER_EDIT: "USER_EDIT",
  USER_DELETE: "USER_DELETE",
  USER_TOGGLE_STATUS: "USER_TOGGLE_STATUS",
  USER_ASSIGN_ROLE: "USER_ASSIGN_ROLE",
  USER_RESET_PASSWORD: "USER_RESET_PASSWORD",
  USER_IMPORT: "USER_IMPORT",

  // Tickets
  TICKET_VIEW_ALL: "TICKET_VIEW_ALL",
  TICKET_VIEW_OWN: "TICKET_VIEW_OWN",
  TICKET_CREATE: "TICKET_CREATE",
  TICKET_EDIT: "TICKET_EDIT",
  TICKET_DELETE: "TICKET_DELETE",
  TICKET_ASSIGN: "TICKET_ASSIGN",
  TICKET_REASSIGN: "TICKET_REASSIGN",
  TICKET_ESCALATE: "TICKET_ESCALATE",
  TICKET_CHANGE_STATUS: "TICKET_CHANGE_STATUS",
  TICKET_CHANGE_PRIORITY: "TICKET_CHANGE_PRIORITY",
  TICKET_ADD_COMMENT: "TICKET_ADD_COMMENT",
  TICKET_EDIT_COMMENT: "TICKET_EDIT_COMMENT",
  TICKET_DELETE_COMMENT: "TICKET_DELETE_COMMENT",
  TICKET_ADD_ATTACHMENT: "TICKET_ADD_ATTACHMENT",
  TICKET_DELETE_ATTACHMENT: "TICKET_DELETE_ATTACHMENT",
  TICKET_MERGE: "TICKET_MERGE",
  TICKET_BULK_UPDATE: "TICKET_BULK_UPDATE",
  TICKET_EXPORT: "TICKET_EXPORT",

  // Ticket Configuration
  TICKET_CONFIG_VIEW: "TICKET_CONFIG_VIEW",
  TICKET_CONFIG_MANAGE_CATEGORIES: "TICKET_CONFIG_MANAGE_CATEGORIES",
  TICKET_CONFIG_MANAGE_STATUSES: "TICKET_CONFIG_MANAGE_STATUSES",
  TICKET_CONFIG_MANAGE_PRIORITIES: "TICKET_CONFIG_MANAGE_PRIORITIES",
  TICKET_CONFIG_MANAGE_TYPES: "TICKET_CONFIG_MANAGE_TYPES",
  TICKET_CONFIG_MANAGE_TEMPLATES: "TICKET_CONFIG_MANAGE_TEMPLATES",

  // Knowledge Base - Legacy permissions (old system)
  KB_VIEW: "KB_VIEW",
  KB_CREATE: "KB_CREATE",
  KB_EDIT: "KB_EDIT",
  KB_DELETE: "KB_DELETE",
  KB_PUBLISH: "KB_PUBLISH",
  KB_UNPUBLISH: "KB_UNPUBLISH",
  KB_MANAGE_CATEGORIES: "KB_MANAGE_CATEGORIES",
  KB_APPROVE: "KB_APPROVE",
  KB_EXPORT: "KB_EXPORT",

  // Knowledge Base - New Modular System
  KB_MANAGE: "KB_MANAGE", // Full KB system admin access
  KB_MANAGE_LEVELS: "KB_MANAGE_LEVELS", // Manage KB levels/categories
  KB_MANAGE_ARTICLES: "KB_MANAGE_ARTICLES", // Manage KB articles
  KB_MANAGE_TABLES: "KB_MANAGE_TABLES", // Manage KB tables
  KB_VIEW_CONTENT: "KB_VIEW_CONTENT", // View KB content only

  // FAQ
  FAQ_VIEW: "FAQ_VIEW",
  FAQ_CREATE: "FAQ_CREATE",
  FAQ_EDIT: "FAQ_EDIT",
  FAQ_DELETE: "FAQ_DELETE",
  FAQ_MANAGE: "FAQ_MANAGE",

  // Feedback Module
  FEEDBACK_FORM_CREATE: "FEEDBACK_FORM_CREATE",
  FEEDBACK_FORM_EDIT: "FEEDBACK_FORM_EDIT",
  FEEDBACK_FORM_DELETE: "FEEDBACK_FORM_DELETE",
  FEEDBACK_VIEW: "FEEDBACK_VIEW",
  FEEDBACK_EXPORT: "FEEDBACK_EXPORT",

  // Offline Module
  OFFLINE_MODULE_ACCESS: "OFFLINE_MODULE_ACCESS",
  OFFLINE_STUDENT_REGISTER: "OFFLINE_STUDENT_REGISTER",
  OFFLINE_TICKET_CREATE: "OFFLINE_TICKET_CREATE",
  OFFLINE_TICKET_RESOLVE: "OFFLINE_TICKET_RESOLVE",
  OFFLINE_TICKET_ESCALATE: "OFFLINE_TICKET_ESCALATE",
  OFFLINE_STUDENT_VIEW: "OFFLINE_STUDENT_VIEW",
  OFFLINE_STUDENT_EDIT: "OFFLINE_STUDENT_EDIT",

  // Audit Logs
  AUDIT_VIEW_ACTIVITY: "AUDIT_VIEW_ACTIVITY",
  AUDIT_VIEW_ACCESS: "AUDIT_VIEW_ACCESS",
  AUDIT_VIEW_BLOCKED_EMAILS: "AUDIT_VIEW_BLOCKED_EMAILS",
  AUDIT_MANAGE_BLOCKED_EMAILS: "AUDIT_MANAGE_BLOCKED_EMAILS",
  AUDIT_VIEW_EMAIL_FAILURES: "AUDIT_VIEW_EMAIL_FAILURES",
  AUDIT_VIEW_INTEGRATION_FAILURES: "AUDIT_VIEW_INTEGRATION_FAILURES",
  AUDIT_VIEW_WEBHOOK_FAILURES: "AUDIT_VIEW_WEBHOOK_FAILURES",
  AUDIT_VIEW_CHAT_WEBHOOK_FAILURES: "AUDIT_VIEW_CHAT_WEBHOOK_FAILURES",
  AUDIT_EXPORT: "AUDIT_EXPORT",

  // SLA & Escalation
  SLA_VIEW: "SLA_VIEW",
  SLA_CREATE: "SLA_CREATE",
  SLA_EDIT: "SLA_EDIT",
  SLA_DELETE: "SLA_DELETE",
  SLA_MANAGE_ESCALATIONS: "SLA_MANAGE_ESCALATIONS",
  SLA_MANAGE_BUSINESS_HOURS: "SLA_MANAGE_BUSINESS_HOURS",

  // Legacy/Alternative naming for backward compatibility
  SLA_MANAGE_ESCALATION: "SLA_MANAGE_ESCALATIONS",

  // Escalation Matrix (Level-based routing system)
  ESCALATION_MATRIX_VIEW: "ESCALATION_MATRIX_VIEW",
  ESCALATION_MATRIX_MANAGE: "ESCALATION_MATRIX_MANAGE",

  // Approval Process
  APPROVAL_WORKFLOWS_VIEW: "APPROVAL_WORKFLOWS_VIEW",
  APPROVAL_WORKFLOWS_CREATE: "APPROVAL_WORKFLOWS_CREATE",
  APPROVAL_WORKFLOWS_EDIT: "APPROVAL_WORKFLOWS_EDIT",
  APPROVAL_WORKFLOWS_DELETE: "APPROVAL_WORKFLOWS_DELETE",
  APPROVAL_TICKETS_APPROVE_REJECT: "APPROVAL_TICKETS_APPROVE_REJECT",
  APPROVAL_HISTORY_VIEW: "APPROVAL_HISTORY_VIEW",

  // Fields & Forms
  FIELDS_VIEW_TICKET_FIELDS: "FIELDS_VIEW_TICKET_FIELDS",
  FIELDS_MANAGE_TICKET_FIELDS: "FIELDS_MANAGE_TICKET_FIELDS",
  FIELDS_MANAGE_TICKET_FORMS: "FIELDS_MANAGE_TICKET_FORMS",
  FIELDS_MANAGE_ACTIVITY_FIELDS: "FIELDS_MANAGE_ACTIVITY_FIELDS",
  FIELDS_MANAGE_USER_FIELDS: "FIELDS_MANAGE_USER_FIELDS",
  FIELDS_MANAGE_CONTACT_FIELDS: "FIELDS_MANAGE_CONTACT_FIELDS",
  FIELDS_MANAGE_DEPENDENCIES: "FIELDS_MANAGE_DEPENDENCIES",

  // Automation
  AUTOMATION_VIEW: "AUTOMATION_VIEW",
  AUTOMATION_MANAGE_AUTO_ASSIGN: "AUTOMATION_MANAGE_AUTO_ASSIGN",
  AUTOMATION_MANAGE_CREATE_TRIGGERS: "AUTOMATION_MANAGE_CREATE_TRIGGERS",
  AUTOMATION_MANAGE_UPDATE_TRIGGERS: "AUTOMATION_MANAGE_UPDATE_TRIGGERS",
  AUTOMATION_MANAGE_TIME_TRIGGERS: "AUTOMATION_MANAGE_TIME_TRIGGERS",
  AUTOMATION_TOGGLE: "AUTOMATION_TOGGLE",

  // Integrations
  INTEGRATION_VIEW: "INTEGRATION_VIEW",
  INTEGRATION_MANAGE_EMAIL: "INTEGRATION_MANAGE_EMAIL",
  INTEGRATION_MANAGE_SMS: "INTEGRATION_MANAGE_SMS",
  INTEGRATION_MANAGE_WEBHOOKS: "INTEGRATION_MANAGE_WEBHOOKS",
  INTEGRATION_MANAGE_API: "INTEGRATION_MANAGE_API",
  INTEGRATION_MANAGE_APPS: "INTEGRATION_MANAGE_APPS",

  // Email Configuration
  EMAIL_CONFIG_VIEW: "EMAIL_CONFIG_VIEW",
  EMAIL_CONFIG_EDIT: "EMAIL_CONFIG_EDIT",
  EMAIL_CONFIG_TEST: "EMAIL_CONFIG_TEST",
  EMAIL_TRIGGER_MANAGE: "EMAIL_TRIGGER_MANAGE",

  // Reports
  REPORT_VIEW_TICKETS: "REPORT_VIEW_TICKETS",
  REPORT_VIEW_AGENT_PERFORMANCE: "REPORT_VIEW_AGENT_PERFORMANCE",
  REPORT_VIEW_CSAT: "REPORT_VIEW_CSAT",
  REPORT_VIEW_SLA: "REPORT_VIEW_SLA",
  REPORT_EXPORT: "REPORT_EXPORT",
  REPORT_CREATE_CUSTOM: "REPORT_CREATE_CUSTOM",
  REPORT_SCHEDULE: "REPORT_SCHEDULE",
  REPORT_ASSIGN: "REPORT_ASSIGN",
  REPORT_DELETE: "REPORT_DELETE",
  REPORT_PERMISSIONS_MANAGE: "REPORT_PERMISSIONS_MANAGE",
  REPORT_DATA_POINTS_MANAGE: "REPORT_DATA_POINTS_MANAGE",

  // Form Builder
  FORM_VIEW: "FORM_VIEW",
  FORM_CREATE: "FORM_CREATE",
  FORM_EDIT: "FORM_EDIT",
  FORM_DELETE: "FORM_DELETE",

  // Asset Management
  ASSET_VIEW: "ASSET_VIEW",
  ASSET_CREATE: "ASSET_CREATE",
  ASSET_EDIT: "ASSET_EDIT",
  ASSET_DELETE: "ASSET_DELETE",
  ASSET_MANAGE: "ASSET_MANAGE",
  ASSET_MAP_TO_CENTER: "ASSET_MAP_TO_CENTER",
  ASSET_UPLOAD_PHOTOS: "ASSET_UPLOAD_PHOTOS",
  ASSET_VIEW_STATS: "ASSET_VIEW_STATS",
  MY_ASSETS_VIEW: "MY_ASSETS_VIEW",

  // Attendance Module
  ATTENDANCE_VIEW: "ATTENDANCE_VIEW",
  ATTENDANCE_REPORT_VIEW: "ATTENDANCE_REPORT_VIEW",
  ATTENDANCE_SYNC: "ATTENDANCE_SYNC",
  ATTENDANCE_CONFIG: "ATTENDANCE_CONFIG",
  ATTENDANCE_EXPORT: "ATTENDANCE_EXPORT",
} as const;

// Permission module prefixes for bulk checks
export const PERMISSION_MODULES = {
  DASHBOARD: "DASHBOARD_",
  PROJECT: "PROJECT_",
  MASTER_DATA: "MASTER_DATA_",
  RBAC: "RBAC_",
  USER: "USER_",
  TICKET: "TICKET_",
  KB: "KB_",
  FAQ: "FAQ_",
  FEEDBACK: "FEEDBACK_",
  OFFLINE: "OFFLINE_",
  AUDIT: "AUDIT_",
  SLA: "SLA_",
  WORKFLOW: "WORKFLOW_",
  APPROVAL: "APPROVAL_",
  FIELDS: "FIELDS_",
  AUTOMATION: "AUTOMATION_",
  INTEGRATION: "INTEGRATION_",
  REPORT: "REPORT_",
  FORM: "FORM_",
  ASSET: "ASSET_",
  ATTENDANCE: "ATTENDANCE_",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
export type PermissionModule =
  (typeof PERMISSION_MODULES)[keyof typeof PERMISSION_MODULES];
