/**
 * Seed Widget Definitions (Phase 1 + Phase 2)
 *
 * Run once at startup (idempotent — uses upsert on widgetKey).
 */

import { WidgetDefinition } from "../models/dashboard/WidgetDefinition";
import { SR_WIDGET_DEFINITIONS } from "./srWidgetDefinitions";

const allWidgets = [
  // ── Phase 1 ──────────────────────────────────────────────────────────────
  {
    widgetKey: "ticket_open_count",
    module: "ticketing",
    displayName: "Open Tickets",
    description: "Current number of tickets that are not closed or resolved.",
    supportedVisualisations: ["kpi_tile", "sparkline"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre", "user"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ticket_open_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_by_status",
    module: "ticketing",
    displayName: "Tickets by Status",
    description: "Breakdown of tickets across all statuses in the date range.",
    supportedVisualisations: ["donut_chart", "bar_chart", "table"],
    defaultVisualisation: "donut_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ticket_by_status",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_sla_resolution_rate",
    module: "ticketing",
    displayName: "SLA Resolution Rate",
    description: "Percentage of closed tickets resolved within SLA due date.",
    supportedVisualisations: ["kpi_tile", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_sla_resolution_rate",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "user_required_vs_onboarded",
    module: "users",
    displayName: "Required vs Onboarded Users",
    description: "Target headcount vs currently onboarded users.",
    supportedVisualisations: ["kpi_tile", "progress_bar"],
    defaultVisualisation: "progress_bar",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 900,
    dataQueryKey: "user_required_vs_onboarded",
    defaultConfig: { filters: {}, targetMode: "project_total" },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "centre_ideal_vs_active",
    module: "users",
    displayName: "Centre: Ideal vs Active Users",
    description: "Per-centre comparison of ideal staffing vs active users.",
    supportedVisualisations: ["bar_chart", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 600,
    dataQueryKey: "centre_ideal_vs_active",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  // ── Phase 2 ──────────────────────────────────────────────────────────────
  {
    widgetKey: "ticket_closed_count",
    module: "ticketing",
    displayName: "Closed Tickets",
    description: "Number of tickets closed or resolved in the date range.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre", "user"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ticket_closed_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_sla_compliance",
    module: "ticketing",
    displayName: "SLA Compliance Rate",
    description: "Percentage of all tickets (open + closed) meeting SLA.",
    supportedVisualisations: ["kpi_tile", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_sla_compliance",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_sla_closed_within",
    module: "ticketing",
    displayName: "Closed/Resolved Within SLA",
    description:
      "Count of closed/resolved tickets (completed in the period) that met SLA.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_sla_closed_within",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_sla_closed_breached",
    module: "ticketing",
    displayName: "Closed/Resolved SLA Breached",
    description:
      "Count of closed/resolved tickets (completed in the period) that missed SLA.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_sla_closed_breached",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_sla_open_within",
    module: "ticketing",
    displayName: "Open Within SLA",
    description:
      "Live count of currently-open tickets still within their SLA target.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ticket_sla_open_within",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_sla_open_breached",
    module: "ticketing",
    displayName: "Open SLA Breached",
    description:
      "Live count of currently-open tickets already past their SLA due time.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ticket_sla_open_breached",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_trend_over_time",
    module: "ticketing",
    displayName: "Ticket Trend (Created vs Closed)",
    description: "Daily count of tickets created and closed over the period.",
    supportedVisualisations: ["line_chart", "bar_chart"],
    defaultVisualisation: "line_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_trend_over_time",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_assignee_workload",
    module: "ticketing",
    displayName: "Agent Workload",
    description: "Open ticket count per agent.",
    supportedVisualisations: ["bar_chart", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ticket_assignee_workload",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "my_assigned_tickets",
    module: "ticketing",
    displayName: "My Open Tickets",
    description: "Open tickets assigned to the viewing user.",
    supportedVisualisations: ["kpi_tile", "table"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["user"],
    cacheTtlSeconds: 60,
    dataQueryKey: "my_assigned_tickets",
    defaultConfig: { filters: { assignedTo: "@ctx.userId", top_n: 25 } },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "user_active_count",
    module: "users",
    displayName: "Active Users",
    description: "Total active users in this project.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 600,
    dataQueryKey: "user_active_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "user_inactive_count",
    module: "users",
    displayName: "Inactive Users",
    description: "Total inactive users in this project.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 600,
    dataQueryKey: "user_inactive_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "user_onboarding_completion_rate",
    module: "users",
    displayName: "Onboarding Completion Rate",
    description: "Percentage of required users that are actively onboarded.",
    supportedVisualisations: ["kpi_tile", "progress_bar", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 900,
    dataQueryKey: "user_onboarding_completion_rate",
    defaultConfig: { filters: {}, targetMode: "project_total" },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "user_by_role",
    module: "users",
    displayName: "Users by Role",
    description: "Active user count grouped by role.",
    supportedVisualisations: ["donut_chart", "bar_chart", "table"],
    defaultVisualisation: "donut_chart",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 600,
    dataQueryKey: "user_by_role",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "centre_capacity_gap",
    module: "users",
    displayName: "Centre Capacity Gap",
    description:
      "Total unfilled seats across all centres (ideal minus active).",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 600,
    dataQueryKey: "centre_capacity_gap",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "centre_capacity_utilisation",
    module: "users",
    displayName: "Centre Capacity Utilisation",
    description: "Percentage of ideal capacity filled across all centres.",
    supportedVisualisations: ["kpi_tile", "gauge", "progress_bar"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 600,
    dataQueryKey: "centre_capacity_utilisation",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "attendance_today_rate",
    module: "attendance",
    displayName: "Attendance Rate — Today",
    description: "Percentage of active users who are present today.",
    supportedVisualisations: ["kpi_tile", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 300,
    dataQueryKey: "attendance_today_rate",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "attendance_mtd_rate",
    module: "attendance",
    displayName: "Attendance Rate – MTD",
    description: "Month-to-date attendance rate across all active users.",
    supportedVisualisations: ["kpi_tile", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 600,
    dataQueryKey: "attendance_mtd_rate",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  // ── Phase 3 (ht_* helpdesk ticketing) ─────────────────────────────────────
  {
    widgetKey: "ht_total_tickets",
    module: "ticketing",
    displayName: "Total Tickets",
    description: "Total ticket count in the date range.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ht_total_tickets",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_open_tickets",
    module: "ticketing",
    displayName: "Open Tickets",
    description: "Currently open tickets.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre", "user"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ht_open_tickets",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_resolved_tickets",
    module: "ticketing",
    displayName: "Resolved Tickets",
    description: "Tickets resolved in the date range.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ht_resolved_tickets",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_closed_tickets",
    module: "ticketing",
    displayName: "Closed Tickets",
    description: "Tickets closed in the date range.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ht_closed_tickets",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_pending_tickets",
    module: "ticketing",
    displayName: "Pending / On-Hold Tickets",
    description: "Tickets currently on hold or pending.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ht_pending_tickets",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_escalated_tickets",
    module: "ticketing",
    displayName: "Escalated Tickets",
    description: "Tickets that have been escalated in the date range.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ht_escalated_tickets",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_sla_breached",
    module: "ticketing",
    displayName: "SLA Breached Tickets",
    description: "Tickets that have breached their SLA in the date range.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ht_sla_breached",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_resolved_within_sla",
    module: "ticketing",
    displayName: "Resolved Within SLA",
    description: "Count of tickets resolved before SLA expiry.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_resolved_within_sla",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_resolution_rate",
    module: "ticketing",
    displayName: "Resolution Rate (%)",
    description: "Percentage of tickets resolved out of total.",
    supportedVisualisations: ["kpi_tile", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_resolution_rate",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_sla_compliance_rate",
    module: "ticketing",
    displayName: "SLA Compliance Rate (%)",
    description: "Percentage of resolved tickets that met their SLA.",
    supportedVisualisations: ["kpi_tile", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_sla_compliance_rate",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_avg_resolution_hours",
    module: "ticketing",
    displayName: "Avg Resolution Time (hrs)",
    description: "Average hours from ticket creation to resolution.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_avg_resolution_hours",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_tickets_by_category",
    module: "ticketing",
    displayName: "Tickets by Category",
    description: "Ticket volume breakdown by category.",
    supportedVisualisations: ["bar_chart", "donut_chart", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_tickets_by_category",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  // ── Category-hierarchy ticket counts (levels 2–5) ─────────────────────────
  // Level 1 is "Tickets by Category" above. Display names follow the typical
  // 5-level config (Category → Subcategory → Topic → Course → Department); the
  // handler resolves actual category names dynamically per project.
  {
    widgetKey: "ht_tickets_by_subcategory",
    module: "ticketing",
    displayName: "Tickets by Subcategory",
    description: "Ticket volume breakdown by Subcategory.",
    supportedVisualisations: ["bar_chart", "donut_chart", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_tickets_by_subcategory",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_tickets_by_topic",
    module: "ticketing",
    displayName: "Tickets by Topic",
    description: "Ticket volume breakdown by Topic.",
    supportedVisualisations: ["bar_chart", "donut_chart", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_tickets_by_topic",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_tickets_by_course",
    module: "ticketing",
    displayName: "Tickets by Course",
    description: "Ticket volume breakdown by Course.",
    supportedVisualisations: ["bar_chart", "donut_chart", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_tickets_by_course",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_tickets_by_department",
    module: "ticketing",
    displayName: "Tickets by Department",
    description: "Ticket volume breakdown by Department.",
    supportedVisualisations: ["bar_chart", "donut_chart", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_tickets_by_department",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  // ── Resolution efficiency (resolved ÷ total %) breakdowns ─────────────────
  {
    widgetKey: "ht_efficiency_by_category",
    module: "ticketing",
    displayName: "Efficiency by Category",
    description: "Resolution rate (resolved ÷ total) per Category.",
    supportedVisualisations: ["table", "bar_chart"],
    defaultVisualisation: "table",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_efficiency_by_category",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_efficiency_by_subcategory",
    module: "ticketing",
    displayName: "Efficiency by Subcategory",
    description: "Resolution rate (resolved ÷ total) per Subcategory.",
    supportedVisualisations: ["table", "bar_chart"],
    defaultVisualisation: "table",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_efficiency_by_subcategory",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_efficiency_by_topic",
    module: "ticketing",
    displayName: "Efficiency by Topic",
    description: "Resolution rate (resolved ÷ total) per Topic.",
    supportedVisualisations: ["table", "bar_chart"],
    defaultVisualisation: "table",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_efficiency_by_topic",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_efficiency_by_course",
    module: "ticketing",
    displayName: "Efficiency by Course",
    description: "Resolution rate (resolved ÷ total) per Course.",
    supportedVisualisations: ["table", "bar_chart"],
    defaultVisualisation: "table",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_efficiency_by_course",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_efficiency_by_department",
    module: "ticketing",
    displayName: "Efficiency by Department",
    description: "Resolution rate (resolved ÷ total) per Department.",
    supportedVisualisations: ["table", "bar_chart"],
    defaultVisualisation: "table",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_efficiency_by_department",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_efficiency_by_center",
    module: "ticketing",
    displayName: "Efficiency by Center",
    description:
      "Resolution rate (resolved ÷ total) per offline center.",
    supportedVisualisations: ["table", "bar_chart"],
    defaultVisualisation: "table",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_efficiency_by_center",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_efficiency_by_user",
    module: "ticketing",
    displayName: "Efficiency by User",
    description:
      "Resolution rate (resolved ÷ total) per assigned user/agent.",
    supportedVisualisations: ["table", "bar_chart"],
    defaultVisualisation: "table",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_efficiency_by_user",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_tickets_by_status",
    module: "ticketing",
    displayName: "Tickets by Status",
    description: "Ticket volume breakdown by status.",
    supportedVisualisations: ["donut_chart", "bar_chart", "table"],
    defaultVisualisation: "donut_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ht_tickets_by_status",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_tickets_by_priority",
    module: "ticketing",
    displayName: "Tickets by Priority",
    description: "Ticket volume breakdown by priority level.",
    supportedVisualisations: ["donut_chart", "bar_chart", "table"],
    defaultVisualisation: "donut_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ht_tickets_by_priority",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_daily_trend",
    module: "ticketing",
    displayName: "Daily Ticket Trend",
    description: "Daily volume of created, resolved, and closed tickets.",
    supportedVisualisations: ["line_chart", "bar_chart", "area_chart"],
    defaultVisualisation: "line_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_daily_trend",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_agent_workload",
    module: "ticketing",
    displayName: "Agent Workload",
    description: "Open, resolved, and closed counts per agent.",
    supportedVisualisations: ["bar_chart", "grouped_bar", "table"],
    defaultVisualisation: "grouped_bar",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ht_agent_workload",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_tickets_heatmap",
    module: "ticketing",
    displayName: "Ticket Volume Heatmap",
    description: "Hour-of-day × day-of-week ticket creation heatmap.",
    supportedVisualisations: ["table"],
    defaultVisualisation: "table",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 600,
    dataQueryKey: "ht_tickets_heatmap",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_first_response_time",
    module: "ticketing",
    displayName: "First Response Time (hrs)",
    description:
      "Average hours between ticket creation and first agent comment.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_first_response_time",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_reopen_rate",
    module: "ticketing",
    displayName: "Ticket Reopen Rate (%)",
    description:
      "Percentage of resolved tickets that were subsequently reopened.",
    supportedVisualisations: ["kpi_tile", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 600,
    dataQueryKey: "ht_reopen_rate",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ht_tickets_by_project",
    module: "ticketing",
    displayName: "Tickets by Project",
    description: "Ticket volume per project (multi-project admins).",
    supportedVisualisations: ["bar_chart", "donut_chart", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ht_tickets_by_project",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  // ── Phase 4 (satisfaction / CSAT-NPS-CES) ────────────────────────────────
  {
    widgetKey: "csat_score",
    module: "satisfaction",
    displayName: "CSAT Score",
    description:
      "Average Customer Satisfaction score (1–5 scale) in the date range.",
    supportedVisualisations: ["kpi_tile", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "csat_score",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "nps_score",
    module: "satisfaction",
    displayName: "NPS Score",
    description: "Net Promoter Score (−100 to +100) based on 0–10 ratings.",
    supportedVisualisations: ["kpi_tile", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "nps_score",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ces_score",
    module: "satisfaction",
    displayName: "CES Score",
    description: "Average Customer Effort Score (1–7 scale) in the date range.",
    supportedVisualisations: ["kpi_tile", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ces_score",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "satisfaction_trend",
    module: "satisfaction",
    displayName: "Satisfaction Trend",
    description: "Daily average CSAT, NPS, and CES scores over the date range.",
    supportedVisualisations: ["line_chart", "area_chart"],
    defaultVisualisation: "line_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 600,
    dataQueryKey: "satisfaction_trend",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "csat_by_agent",
    module: "satisfaction",
    displayName: "CSAT by Agent",
    description: "Average CSAT score per support agent.",
    supportedVisualisations: ["bar_chart", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "csat_by_agent",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "feedback_response_rate",
    module: "satisfaction",
    displayName: "Feedback Response Rate (%)",
    description:
      "Percentage of closed tickets that received a satisfaction response.",
    supportedVisualisations: ["kpi_tile", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "feedback_response_rate",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },

  // ── Phase 2 update: my_assigned_tickets now also supports table view ───────
  // (The upsert will merge the new supportedVisualisations onto the existing doc)

  // ── Phase 5 — Supplementary ticket handlers ───────────────────────────────
  {
    widgetKey: "ticket_escalated_this_period",
    module: "ticketing",
    displayName: "Escalated This Period",
    description:
      "Tickets that had a new escalation event within the date range.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ticket_escalated_this_period",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_inprogress_count",
    module: "ticketing",
    displayName: "In-Progress Tickets",
    description:
      "Tickets currently in non-default, non-closed statuses (agent has touched but not resolved).",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 60,
    dataQueryKey: "ticket_inprogress_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_resolved_count",
    module: "ticketing",
    displayName: "Resolved Tickets",
    description: "Tickets moved to a closed status within the date range.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ticket_resolved_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_onhold_count",
    module: "ticketing",
    displayName: "On-Hold Tickets",
    description:
      "Tickets currently on hold (maps to pending statuses; see ticket_inprogress_count).",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 60,
    dataQueryKey: "ticket_onhold_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_by_submission_source",
    module: "ticketing",
    displayName: "Tickets by Submission Source",
    description: "Ticket volume breakdown by submission channel.",
    supportedVisualisations: ["donut_chart", "bar_chart", "table"],
    defaultVisualisation: "donut_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_by_submission_source",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_recent_list",
    module: "ticketing",
    displayName: "Recent Tickets",
    description: "Latest open tickets sorted by creation date.",
    supportedVisualisations: ["table"],
    defaultVisualisation: "table",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 60,
    dataQueryKey: "ticket_recent_list",
    defaultConfig: { filters: { top_n: 20 } },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_comment_count",
    module: "ticketing",
    displayName: "Total Comments (Open Tickets)",
    description: "Cumulative comment count across all open tickets in range.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_comment_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },

  // ── Phase 5 — Catalogue-key aliases (reuse ht_* execute logic) ────────────
  {
    widgetKey: "ticket_by_priority",
    module: "ticketing",
    displayName: "Tickets by Priority",
    description:
      "Alias for ht_tickets_by_priority — breakdown by priority level.",
    supportedVisualisations: ["donut_chart", "bar_chart", "table"],
    defaultVisualisation: "donut_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ticket_by_priority",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_by_category",
    module: "ticketing",
    displayName: "Tickets by Category",
    description: "Alias for ht_tickets_by_category — breakdown by category.",
    supportedVisualisations: ["bar_chart", "donut_chart", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_by_category",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_volume_trend",
    module: "ticketing",
    displayName: "Ticket Volume Trend",
    description: "Alias for ht_daily_trend — daily created vs closed series.",
    supportedVisualisations: ["line_chart", "area_chart", "bar_chart"],
    defaultVisualisation: "line_chart",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_volume_trend",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_escalation_count",
    module: "ticketing",
    displayName: "Escalation Count",
    description:
      "Alias for ht_escalated_tickets — tickets ever escalated in range.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ticket_escalation_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_first_response_time",
    module: "ticketing",
    displayName: "First Response Time (hrs)",
    description:
      "Alias for ht_first_response_time — avg hours to first response.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_first_response_time",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_avg_resolution_time",
    module: "ticketing",
    displayName: "Avg Resolution Time (hrs)",
    description:
      "Alias for ht_avg_resolution_hours — mean hours from open to close.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_avg_resolution_time",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_resolution_rate",
    module: "ticketing",
    displayName: "Ticket Resolution Rate (%)",
    description:
      "Alias for ht_resolution_rate — % of tickets resolved in range.",
    supportedVisualisations: ["kpi_tile", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_resolution_rate",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },

  // ── Phase 5 — User analytics ───────────────────────────────────────────────
  {
    widgetKey: "user_total_count",
    module: "users",
    displayName: "Total Users",
    description: "Total users (active + inactive) in the project.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 600,
    dataQueryKey: "user_total_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "user_new_registrations",
    module: "users",
    displayName: "New Registrations",
    description: "Users created within the date range.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 600,
    dataQueryKey: "user_new_registrations",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "user_by_registration_source",
    module: "users",
    displayName: "Users by Registration Source",
    description: "Breakdown of active users by how they were registered.",
    supportedVisualisations: ["donut_chart", "bar_chart", "table"],
    defaultVisualisation: "donut_chart",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 900,
    dataQueryKey: "user_by_registration_source",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "user_never_logged_in",
    module: "users",
    displayName: "Users Never Logged In",
    description: "Active users who have never logged into the system.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 900,
    dataQueryKey: "user_never_logged_in",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "user_by_department",
    module: "users",
    displayName: "Users by Department",
    description: "Active user count broken down by department.",
    supportedVisualisations: ["bar_chart", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 900,
    dataQueryKey: "user_by_department",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "user_eula_acceptance_rate",
    module: "users",
    displayName: "EULA Acceptance Rate (%)",
    description: "Percentage of active users who have accepted the EULA.",
    supportedVisualisations: ["kpi_tile", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 900,
    dataQueryKey: "user_eula_acceptance_rate",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "user_password_setup_pending",
    module: "users",
    displayName: "Password Setup Pending",
    description:
      "Active users who have not yet completed initial password setup.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 600,
    dataQueryKey: "user_password_setup_pending",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },

  // ── Knowledge Base handlers ───────────────────────────────────────────────
  {
    widgetKey: "kb_total_articles",
    module: "knowledge_base",
    displayName: "Total KB Articles",
    description: "Total active articles in the project knowledge base.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 900,
    dataQueryKey: "kb_total_articles",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "kb_published_count",
    module: "knowledge_base",
    displayName: "Published Articles",
    description: "Count of published KB articles.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 900,
    dataQueryKey: "kb_published_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "kb_draft_count",
    module: "knowledge_base",
    displayName: "Draft Articles",
    description: "Count of KB articles currently in draft status.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 900,
    dataQueryKey: "kb_draft_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "kb_archived_count",
    module: "knowledge_base",
    displayName: "Archived Articles",
    description: "Count of archived KB articles.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 900,
    dataQueryKey: "kb_archived_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "kb_top_viewed",
    module: "knowledge_base",
    displayName: "Top Viewed Articles",
    description: "Most viewed KB articles ranked by view count.",
    supportedVisualisations: ["table"],
    defaultVisualisation: "table",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 600,
    dataQueryKey: "kb_top_viewed",
    defaultConfig: { filters: { top_n: 10 } },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "kb_helpfulness_rate",
    module: "knowledge_base",
    displayName: "KB Helpfulness Rate (%)",
    description:
      "Percentage of helpful votes vs total votes across all published articles.",
    supportedVisualisations: ["kpi_tile", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 900,
    dataQueryKey: "kb_helpfulness_rate",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "kb_recent_updates",
    module: "knowledge_base",
    displayName: "Recently Updated Articles",
    description: "KB articles sorted by most recent update.",
    supportedVisualisations: ["table"],
    defaultVisualisation: "table",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 300,
    dataQueryKey: "kb_recent_updates",
    defaultConfig: { filters: { top_n: 10 } },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "kb_by_category",
    module: "knowledge_base",
    displayName: "Articles by Category",
    description: "Published KB article count broken down by category.",
    supportedVisualisations: ["bar_chart", "donut_chart", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 900,
    dataQueryKey: "kb_by_category",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },

  // ── Activity / Access / Email log handlers ────────────────────────────────
  {
    widgetKey: "activity_feed",
    module: "activity",
    displayName: "Activity Feed",
    description: "Recent agent activity events (creates, updates, deletes).",
    supportedVisualisations: ["table"],
    defaultVisualisation: "table",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 60,
    dataQueryKey: "activity_feed",
    defaultConfig: { filters: { top_n: 20 } },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "login_failure_count",
    module: "security",
    displayName: "Login Failures",
    description: "Count of failed login attempts in the date range.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 120,
    dataQueryKey: "login_failure_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "active_session_count",
    module: "security",
    displayName: "Active Sessions Today",
    description: "Distinct users who logged in successfully today.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 120,
    dataQueryKey: "active_session_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "email_sent_count",
    module: "email",
    displayName: "Emails Sent",
    description: "Count of successfully delivered emails in the date range.",
    supportedVisualisations: ["kpi_tile"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 300,
    dataQueryKey: "email_sent_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "email_failure_rate",
    module: "email",
    displayName: "Email Failure Rate (%)",
    description: "Percentage of emails that failed to send in the date range.",
    supportedVisualisations: ["kpi_tile", "gauge"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 300,
    dataQueryKey: "email_failure_rate",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "email_by_type",
    module: "email",
    displayName: "Emails by Type",
    description:
      "Email volume breakdown by email type (OTP, ticket, welcome, etc.).",
    supportedVisualisations: ["donut_chart", "bar_chart", "table"],
    defaultVisualisation: "donut_chart",
    scopeLevels: ["tenant"],
    cacheTtlSeconds: 600,
    dataQueryKey: "email_by_type",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },

  // ── Footfall ──────────────────────────────────────────────────────────────
  {
    widgetKey: "ticket_footfall_count",
    module: "ticketing",
    displayName: "Footfall Count",
    description:
      "New queries created + existing queries that got a reply/comment, over the selected period.",
    supportedVisualisations: ["kpi_tile", "sparkline"],
    defaultVisualisation: "kpi_tile",
    scopeLevels: ["tenant", "project", "centre"],
    cacheTtlSeconds: 120,
    dataQueryKey: "ticket_footfall_count",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_footfall_trend",
    module: "ticketing",
    displayName: "Footfall Trend",
    description:
      "Daily footfall (new queries created + existing queries with a reply/comment that day).",
    supportedVisualisations: ["line_chart", "bar_chart"],
    defaultVisualisation: "line_chart",
    scopeLevels: ["tenant", "project", "centre"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_footfall_trend",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  {
    widgetKey: "ticket_footfall_by_center",
    module: "ticketing",
    displayName: "Footfall by Centre",
    description: "Footfall count grouped by centre.",
    supportedVisualisations: ["bar_chart", "table"],
    defaultVisualisation: "bar_chart",
    scopeLevels: ["tenant", "project"],
    cacheTtlSeconds: 300,
    dataQueryKey: "ticket_footfall_by_center",
    defaultConfig: { filters: {} },
    isActive: true,
    version: 1,
  },
  ...SR_WIDGET_DEFINITIONS,
];

export async function seedWidgetDefinitions(): Promise<void> {
  for (const widget of allWidgets) {
    await WidgetDefinition.findOneAndUpdate(
      { widgetKey: widget.widgetKey },
      { $set: widget },
      { upsert: true, new: true },
    );
  }
  console.log(
    `📊 Dashboard Engine: Seeded ${allWidgets.length} widget definitions (Phase 1–5 + KB + Activity + Security + Email)`,
  );
}
