import mongoose, { Document, Schema } from "mongoose";

export type DataPointCategory =
  | "ticket"
  | "agent"
  | "customer"
  | "sla"
  | "channel"
  | "feedback"
  | "footfall"
  | "custom_form"
  | "user"
  | "asset"
  | "asset_audit"
  | "asset_inventory"
  | "service_request"
  | "call"
  | "email_intake"
  | "inquiry";
export type FieldType = "string" | "number" | "date" | "boolean" | "array";

/** Base collection a data point is queried from. Existing points default to ticket. */
export type DataPointSource =
  | "ticket"
  | "user"
  | "asset"
  | "asset_audit"
  | "asset_inventory"
  | "feedback"
  | "service_request"
  | "call"
  | "email_intake"
  | "inquiry";

/**
 * Registry of all available data points in the Report module.
 * These are seeded at startup and referenced by key throughout the system.
 * isSystem=true means the record cannot be deleted by users.
 */
export interface IReportDataPoint extends Document {
  key: string; // unique slug, e.g. 'ticket_number'
  label: string; // UI label, e.g. 'Ticket #'
  description: string;
  category: DataPointCategory;
  /** Base collection this data point reports from (default 'ticket'). */
  source?: DataPointSource;
  fieldPath: string; // computed field name after aggregation (not raw MongoDB path)
  fieldType: FieldType;
  isActive: boolean;
  isSystem: boolean;
  order: number;
  createdAt: Date;
  updatedAt: Date;
}

const ReportDataPointSchema = new Schema<IReportDataPoint>(
  {
    key: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
    },
    label: { type: String, required: true },
    description: { type: String, default: "" },
    category: {
      type: String,
      enum: [
        "ticket",
        "agent",
        "customer",
        "sla",
        "channel",
        "feedback",
        "footfall",
        "custom_form",
        "user",
        "asset",
        "asset_audit",
        "asset_inventory",
        "service_request",
        "call",
        "email_intake",
        "inquiry",
      ],
      required: true,
    },
    source: {
      type: String,
      enum: [
        "ticket",
        "user",
        "asset",
        "asset_audit",
        "asset_inventory",
        "feedback",
        "service_request",
        "call",
        "email_intake",
        "inquiry",
      ],
      default: "ticket",
    },
    fieldPath: { type: String, required: true },
    fieldType: {
      type: String,
      enum: ["string", "number", "date", "boolean", "array"],
      required: true,
    },
    isActive: { type: Boolean, default: true },
    isSystem: { type: Boolean, default: true },
    order: { type: Number, default: 0 },
  },
  { timestamps: true },
);

export const ReportDataPoint = mongoose.model<IReportDataPoint>(
  "ReportDataPoint",
  ReportDataPointSchema,
);

/** The canonical seed list for all system data points. Imported by the controller seed function. */
export const SYSTEM_DATA_POINTS: Omit<
  IReportDataPoint,
  keyof Document | "createdAt" | "updatedAt"
>[] = [
  // ── TICKET GROUP ───────────────────────────────────────────────────────────
  {
    key: "ticket_number",
    label: "Ticket #",
    description: "Unique ticket identifier",
    category: "ticket",
    fieldPath: "ticketNumber",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 1,
  },
  {
    key: "ticket_subject",
    label: "Subject",
    description: "Ticket title or subject line",
    category: "ticket",
    fieldPath: "subject",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 2,
  },
  {
    key: "ticket_status",
    label: "Status",
    description: "Current status (Open, In Progress, Resolved…)",
    category: "ticket",
    fieldPath: "statusLabel",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 3,
  },
  {
    key: "ticket_priority",
    label: "Priority",
    description: "Ticket priority level",
    category: "ticket",
    fieldPath: "priority",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 4,
  },
  {
    key: "ticket_category",
    label: "Category",
    description: "Category / sub-category hierarchy (full path)",
    category: "ticket",
    fieldPath: "categoryDisplay",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 5,
  },
  {
    key: "ticket_assigned_to",
    label: "Assigned Agent",
    description: "Full name of the assigned agent",
    category: "ticket",
    fieldPath: "assignedToName",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 6,
  },
  {
    key: "ticket_created_by",
    label: "Submitted By",
    description: "Full name of the ticket submitter",
    category: "ticket",
    fieldPath: "createdByName",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 7,
  },
  {
    key: "ticket_created_at",
    label: "Created Date",
    description: "Date and time the ticket was created",
    category: "ticket",
    fieldPath: "createdAt",
    fieldType: "date",
    isActive: true,
    isSystem: true,
    order: 8,
  },
  {
    key: "ticket_resolved_at",
    label: "Resolved Date",
    description: "Date and time the ticket was resolved",
    category: "ticket",
    fieldPath: "resolvedAt",
    fieldType: "date",
    isActive: true,
    isSystem: true,
    order: 9,
  },
  {
    key: "ticket_closed_at",
    label: "Closed Date",
    description: "Date and time the ticket was closed",
    category: "ticket",
    fieldPath: "closedAt",
    fieldType: "date",
    isActive: true,
    isSystem: true,
    order: 10,
  },
  {
    key: "ticket_resolution_time_hrs",
    label: "Resolution Time (hrs)",
    description: "Hours between ticket creation and resolution",
    category: "ticket",
    fieldPath: "resolutionTimeHrs",
    fieldType: "number",
    isActive: true,
    isSystem: true,
    order: 11,
  },
  {
    key: "ticket_sla_status",
    label: "SLA Status",
    description: "Whether the ticket met its SLA",
    category: "ticket",
    fieldPath: "slaStatus",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 12,
  },
  {
    key: "ticket_sla_due_at",
    label: "SLA Due Date",
    description: "SLA deadline for this ticket",
    category: "ticket",
    fieldPath: "slaDueAt",
    fieldType: "date",
    isActive: true,
    isSystem: true,
    order: 13,
  },
  {
    key: "ticket_sla_breached_at",
    label: "SLA Breached At",
    description: "Date the SLA was breached (if applicable)",
    category: "ticket",
    fieldPath: "slaBreachedAt",
    fieldType: "date",
    isActive: true,
    isSystem: true,
    order: 14,
  },
  {
    key: "ticket_source",
    label: "Source Channel",
    description: "How the ticket was submitted (email, portal…)",
    category: "ticket",
    fieldPath: "submissionSource",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 15,
  },
  {
    key: "ticket_tags",
    label: "Tags",
    description: "Tags attached to the ticket",
    category: "ticket",
    fieldPath: "tags",
    fieldType: "array",
    isActive: true,
    isSystem: true,
    order: 16,
  },
  {
    key: "ticket_project",
    label: "Project",
    description: "Project the ticket belongs to",
    category: "ticket",
    fieldPath: "projectName",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 17,
  },
  {
    key: "ticket_escalation_level",
    label: "Escalation Level",
    description: "Current escalation level number",
    category: "ticket",
    fieldPath: "currentEscalationLevelNumber",
    fieldType: "number",
    isActive: true,
    isSystem: true,
    order: 18,
  },
  {
    key: "ticket_assigned_via",
    label: "Assignment Method",
    description: "How the ticket was assigned (manual, round-robin…)",
    category: "ticket",
    fieldPath: "assignedVia",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 19,
  },
  {
    key: "ticket_escalation_count",
    label: "# Escalations",
    description: "Total number of times ticket was escalated",
    category: "ticket",
    fieldPath: "escalationCount",
    fieldType: "number",
    isActive: true,
    isSystem: true,
    order: 20,
  },

  // ── CUSTOMER / SUBMITTER GROUP ─────────────────────────────────────────────
  {
    key: "customer_name",
    label: "Customer Name",
    description: "Full name of the ticket submitter",
    category: "customer",
    fieldPath: "createdByName",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 30,
  },
  {
    key: "customer_email",
    label: "Customer Email",
    description: "Email address of the ticket submitter",
    category: "customer",
    fieldPath: "createdByEmail",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 31,
  },
  {
    key: "customer_department",
    label: "Department",
    description: "Submitter's department",
    category: "customer",
    fieldPath: "createdByDepartment",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 32,
  },
  {
    key: "customer_unique_id",
    label: "Student / Employee ID",
    description: "Submitter's unique identifier",
    category: "customer",
    fieldPath: "createdByUniqueId",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 33,
  },

  // ── SLA GROUP ──────────────────────────────────────────────────────────────
  {
    key: "sla_response_sla_hrs",
    label: "Response SLA (hrs)",
    description: "Expected first-response time from SLA rule",
    category: "sla",
    fieldPath: "responseSlaHrs",
    fieldType: "number",
    isActive: true,
    isSystem: true,
    order: 40,
  },
  {
    key: "sla_resolution_sla_hrs",
    label: "Resolution SLA (hrs)",
    description: "Expected resolution time from SLA rule",
    category: "sla",
    fieldPath: "resolutionSlaHrs",
    fieldType: "number",
    isActive: true,
    isSystem: true,
    order: 41,
  },

  // ── CHANNEL GROUP ─────────────────────────────────────────────────────────
  {
    key: "channel_source_email",
    label: "Source Email Address",
    description: "Inbound email address that created the ticket",
    category: "channel",
    fieldPath: "sourceEmail",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 50,
  },
  {
    key: "channel_offline_center",
    label: "Offline Center",
    description: "Walk-in center name for offline (in-person) tickets",
    category: "channel",
    fieldPath: "centerName",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 51,
  },
  {
    key: "channel_district",
    label: "District",
    description: "District of the ticket's centre (from the centre address)",
    category: "channel",
    fieldPath: "centerDistrict",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 52,
  },

  // ── AGENT GROUP ───────────────────────────────────────────────────────────
  {
    key: "agent_role_name",
    label: "Agent Role",
    description: "Role name of the agent assigned to the ticket",
    category: "agent",
    fieldPath: "assignedToRoleName",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 70,
  },

  // ── FEEDBACK GROUP ────────────────────────────────────────────────────────
  {
    key: "feedback_csat_score",
    label: "CSAT Score",
    description: "Customer satisfaction score from feedback form",
    category: "feedback",
    fieldPath: "csatScore",
    fieldType: "number",
    isActive: true,
    isSystem: true,
    order: 60,
  },
  {
    key: "feedback_comment",
    label: "Feedback Comment",
    description: "Free-text feedback comment left by customer",
    category: "feedback",
    fieldPath: "feedbackComment",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 61,
  },

  // ── FOOTFALL GROUP ────────────────────────────────────────────────────────
  {
    key: "student_portal_email",
    label: "Student Portal Email",
    description: "Email used by the student when submitting via portal",
    category: "footfall",
    fieldPath: "studentPortalEmail",
    fieldType: "string",
    isActive: true,
    isSystem: true,
    order: 90,
  },
  {
    key: "ticket_response_count",
    label: "Response Count",
    description: "Number of follow-up responses/comments on this ticket",
    category: "footfall",
    fieldPath: "responseCount",
    fieldType: "number",
    isActive: true,
    isSystem: true,
    order: 91,
  },

  // ── USER GROUP (source: user) ──────────────────────────────────────────────
  { key: "user_name", label: "Name", description: "User full name", category: "user", source: "user", fieldPath: "userName", fieldType: "string", isActive: true, isSystem: true, order: 200 },
  { key: "user_email", label: "Email", description: "User email address", category: "user", source: "user", fieldPath: "email", fieldType: "string", isActive: true, isSystem: true, order: 201 },
  { key: "user_mobile", label: "Mobile", description: "User mobile number", category: "user", source: "user", fieldPath: "mobile", fieldType: "string", isActive: true, isSystem: true, order: 202 },
  { key: "user_employee_code", label: "Employee Code", description: "Employee / staff code", category: "user", source: "user", fieldPath: "employeeCode", fieldType: "string", isActive: true, isSystem: true, order: 203 },
  { key: "user_role", label: "Role", description: "Assigned role name", category: "user", source: "user", fieldPath: "roleName", fieldType: "string", isActive: true, isSystem: true, order: 204 },
  { key: "user_department", label: "Department", description: "User department", category: "user", source: "user", fieldPath: "department", fieldType: "string", isActive: true, isSystem: true, order: 205 },
  { key: "user_payroll_type", label: "Payroll Type", description: "Internal / external payroll", category: "user", source: "user", fieldPath: "payrollType", fieldType: "string", isActive: true, isSystem: true, order: 206 },
  { key: "user_projects", label: "Projects", description: "Projects the user belongs to", category: "user", source: "user", fieldPath: "projectNames", fieldType: "string", isActive: true, isSystem: true, order: 207 },
  { key: "user_centers", label: "Centers", description: "Centers assigned to the user", category: "user", source: "user", fieldPath: "centerNames", fieldType: "string", isActive: true, isSystem: true, order: 208 },
  { key: "user_status", label: "Status", description: "Active / Inactive", category: "user", source: "user", fieldPath: "statusLabel", fieldType: "string", isActive: true, isSystem: true, order: 209 },
  { key: "user_last_login", label: "Last Login", description: "Last login date/time", category: "user", source: "user", fieldPath: "lastLogin", fieldType: "date", isActive: true, isSystem: true, order: 210 },
  { key: "user_created_at", label: "Created Date", description: "Account creation date", category: "user", source: "user", fieldPath: "createdAt", fieldType: "date", isActive: true, isSystem: true, order: 211 },

  // ── ASSET GROUP (source: asset) ────────────────────────────────────────────
  { key: "asset_name", label: "Asset Name", description: "Name of the asset", category: "asset", source: "asset", fieldPath: "name", fieldType: "string", isActive: true, isSystem: true, order: 300 },
  { key: "asset_category", label: "Asset Category", description: "Asset category", category: "asset", source: "asset", fieldPath: "categoryName", fieldType: "string", isActive: true, isSystem: true, order: 301 },
  { key: "asset_count", label: "Predefined Count", description: "Configured asset quantity", category: "asset", source: "asset", fieldPath: "predefinedCount", fieldType: "number", isActive: true, isSystem: true, order: 302 },
  { key: "asset_unit", label: "Unit", description: "Unit of measure", category: "asset", source: "asset", fieldPath: "unit", fieldType: "string", isActive: true, isSystem: true, order: 303 },
  { key: "asset_project", label: "Project", description: "Project the asset belongs to", category: "asset", source: "asset", fieldPath: "projectName", fieldType: "string", isActive: true, isSystem: true, order: 304 },
  { key: "asset_status", label: "Status", description: "Active / Inactive", category: "asset", source: "asset", fieldPath: "statusLabel", fieldType: "string", isActive: true, isSystem: true, order: 305 },
  { key: "asset_created_at", label: "Created Date", description: "When the asset was created", category: "asset", source: "asset", fieldPath: "createdAt", fieldType: "date", isActive: true, isSystem: true, order: 306 },

  // ── ASSET AUDIT GROUP (source: asset_audit) ────────────────────────────────
  { key: "audit_asset_name", label: "Asset", description: "Audited asset name", category: "asset_audit", source: "asset_audit", fieldPath: "assetName", fieldType: "string", isActive: true, isSystem: true, order: 400 },
  { key: "audit_center", label: "Offline Center", description: "Offline center where the audit happened", category: "asset_audit", source: "asset_audit", fieldPath: "centerName", fieldType: "string", isActive: true, isSystem: true, order: 401 },
  { key: "audit_change_type", label: "Change Type", description: "working / not-working / both", category: "asset_audit", source: "asset_audit", fieldPath: "changeType", fieldType: "string", isActive: true, isSystem: true, order: 402 },
  { key: "audit_prev_working", label: "Prev Working", description: "Working count before change", category: "asset_audit", source: "asset_audit", fieldPath: "prevWorking", fieldType: "number", isActive: true, isSystem: true, order: 403 },
  { key: "audit_prev_notworking", label: "Prev Not-Working", description: "Not-working count before change", category: "asset_audit", source: "asset_audit", fieldPath: "prevNotWorking", fieldType: "number", isActive: true, isSystem: true, order: 404 },
  { key: "audit_curr_working", label: "New Working", description: "Working count after change", category: "asset_audit", source: "asset_audit", fieldPath: "currWorking", fieldType: "number", isActive: true, isSystem: true, order: 405 },
  { key: "audit_curr_notworking", label: "New Not-Working", description: "Not-working count after change", category: "asset_audit", source: "asset_audit", fieldPath: "currNotWorking", fieldType: "number", isActive: true, isSystem: true, order: 406 },
  { key: "audit_changed_by", label: "Changed By", description: "User who made the change", category: "asset_audit", source: "asset_audit", fieldPath: "changedByName", fieldType: "string", isActive: true, isSystem: true, order: 407 },
  { key: "audit_changed_at", label: "Changed At", description: "When the audit change was made", category: "asset_audit", source: "asset_audit", fieldPath: "changedAt", fieldType: "date", isActive: true, isSystem: true, order: 408 },
  { key: "audit_remarks", label: "Remarks", description: "Audit remarks/notes", category: "asset_audit", source: "asset_audit", fieldPath: "remarks", fieldType: "string", isActive: true, isSystem: true, order: 409 },

  // ── ASSET INVENTORY GROUP (source: asset_inventory — CenterAssetMapping) ────
  { key: "inv_asset_name", label: "Asset", description: "Asset name", category: "asset_inventory", source: "asset_inventory", fieldPath: "assetName", fieldType: "string", isActive: true, isSystem: true, order: 450 },
  { key: "inv_center", label: "Offline Center", description: "Offline center the asset is mapped to", category: "asset_inventory", source: "asset_inventory", fieldPath: "centerName", fieldType: "string", isActive: true, isSystem: true, order: 451 },
  { key: "inv_project", label: "Project", description: "Project", category: "asset_inventory", source: "asset_inventory", fieldPath: "projectName", fieldType: "string", isActive: true, isSystem: true, order: 452 },
  { key: "inv_total_assigned", label: "Total Assigned", description: "Total assets assigned", category: "asset_inventory", source: "asset_inventory", fieldPath: "totalAssigned", fieldType: "number", isActive: true, isSystem: true, order: 453 },
  { key: "inv_used", label: "Used", description: "Assets in use", category: "asset_inventory", source: "asset_inventory", fieldPath: "assetUsed", fieldType: "number", isActive: true, isSystem: true, order: 454 },
  { key: "inv_not_used", label: "Not Used", description: "Assets not in use", category: "asset_inventory", source: "asset_inventory", fieldPath: "assetNotUsed", fieldType: "number", isActive: true, isSystem: true, order: 455 },
  { key: "inv_working", label: "Working", description: "Working asset count", category: "asset_inventory", source: "asset_inventory", fieldPath: "workingAsset", fieldType: "number", isActive: true, isSystem: true, order: 456 },
  { key: "inv_not_working", label: "Not Working", description: "Not-working asset count", category: "asset_inventory", source: "asset_inventory", fieldPath: "notWorkingAsset", fieldType: "number", isActive: true, isSystem: true, order: 457 },
  { key: "inv_remark", label: "Remark", description: "Inventory remark/notes", category: "asset_inventory", source: "asset_inventory", fieldPath: "remark", fieldType: "string", isActive: true, isSystem: true, order: 458 },
  { key: "inv_audit_submitted", label: "Audit Submitted", description: "Whether the current audit cycle is submitted", category: "asset_inventory", source: "asset_inventory", fieldPath: "auditSubmittedLabel", fieldType: "string", isActive: true, isSystem: true, order: 459 },
  { key: "inv_last_audit_submitted_by", label: "Audit Submitted By", description: "Who submitted the last audit", category: "asset_inventory", source: "asset_inventory", fieldPath: "auditSubmittedByName", fieldType: "string", isActive: true, isSystem: true, order: 460 },
  { key: "inv_last_audit_submitted_at", label: "Audit Submitted At", description: "When the last audit was submitted", category: "asset_inventory", source: "asset_inventory", fieldPath: "lastAuditSubmittedAt", fieldType: "date", isActive: true, isSystem: true, order: 461 },
  { key: "inv_last_audit_date", label: "Last Audit Date", description: "Configured last audit date", category: "asset_inventory", source: "asset_inventory", fieldPath: "lastAuditDate", fieldType: "date", isActive: true, isSystem: true, order: 462 },
  { key: "inv_next_audit_date", label: "Next Audit Date", description: "When the next audit is due", category: "asset_inventory", source: "asset_inventory", fieldPath: "nextAuditDate", fieldType: "date", isActive: true, isSystem: true, order: 463 },
  { key: "inv_audit_frequency", label: "Audit Frequency (months)", description: "Audit frequency in months", category: "asset_inventory", source: "asset_inventory", fieldPath: "auditFrequencyMonths", fieldType: "number", isActive: true, isSystem: true, order: 464 },
  { key: "inv_updated_by", label: "Last Updated By", description: "Who last updated this inventory record", category: "asset_inventory", source: "asset_inventory", fieldPath: "updatedByName", fieldType: "string", isActive: true, isSystem: true, order: 465 },
  { key: "inv_updated_at", label: "Last Updated At", description: "When the inventory record was last updated", category: "asset_inventory", source: "asset_inventory", fieldPath: "updatedAt", fieldType: "date", isActive: true, isSystem: true, order: 466 },

  // ── FEEDBACK GROUP (source: feedback — direct from FeedbackResponse) ────────
  { key: "fbr_rating", label: "Overall Rating", description: "Overall feedback rating", category: "feedback", source: "feedback", fieldPath: "rating", fieldType: "number", isActive: true, isSystem: true, order: 500 },
  { key: "fbr_submitted_at", label: "Submitted Date", description: "When the feedback was submitted", category: "feedback", source: "feedback", fieldPath: "submittedAt", fieldType: "date", isActive: true, isSystem: true, order: 501 },
  { key: "fbr_ticket_number", label: "Ticket #", description: "Ticket the feedback is for", category: "feedback", source: "feedback", fieldPath: "ticketNumber", fieldType: "string", isActive: true, isSystem: true, order: 502 },
  { key: "fbr_submitter", label: "Submitted By", description: "Student / submitter name", category: "feedback", source: "feedback", fieldPath: "submitterName", fieldType: "string", isActive: true, isSystem: true, order: 503 },
  { key: "fbr_project", label: "Project", description: "Project the feedback belongs to", category: "feedback", source: "feedback", fieldPath: "projectName", fieldType: "string", isActive: true, isSystem: true, order: 504 },
  { key: "fbr_form", label: "Feedback Form", description: "Name of the feedback form", category: "feedback", source: "feedback", fieldPath: "formName", fieldType: "string", isActive: true, isSystem: true, order: 505 },
  { key: "fbr_answers_count", label: "# Answers", description: "Number of answered questions", category: "feedback", source: "feedback", fieldPath: "answersCount", fieldType: "number", isActive: true, isSystem: true, order: 506 },
  { key: "fbr_answers", label: "Answers", description: "All question/answer pairs", category: "feedback", source: "feedback", fieldPath: "answersText", fieldType: "string", isActive: true, isSystem: true, order: 507 },
  { key: "fbr_center", label: "Offline Center", description: "Offline center of the ticket this feedback is for", category: "feedback", source: "feedback", fieldPath: "centerName", fieldType: "string", isActive: true, isSystem: true, order: 508 },
  { key: "fbr_district", label: "District", description: "District of the ticket's offline center", category: "feedback", source: "feedback", fieldPath: "centerDistrict", fieldType: "string", isActive: true, isSystem: true, order: 509 },

  // ── SERVICE REQUEST GROUP (source: ticket — PSR/ISR live on the ticket spine) ─
  { key: "sr_interaction_type", label: "Request Type", description: "Normal / PSR / ISR (interaction type)", category: "service_request", source: "service_request", fieldPath: "interactionTypeLabel", fieldType: "string", isActive: true, isSystem: true, order: 600 },
  { key: "sr_cancelled", label: "Cancelled?", description: "Whether the SR was cancelled", category: "service_request", source: "service_request", fieldPath: "srCancelledLabel", fieldType: "string", isActive: true, isSystem: true, order: 601 },
  { key: "sr_cancel_reason", label: "Cancellation Reason", description: "Reason captured when the SR was cancelled", category: "service_request", source: "service_request", fieldPath: "srCancelReason", fieldType: "string", isActive: true, isSystem: true, order: 602 },
  { key: "sr_reopened", label: "Re-opened?", description: "Whether the SR was re-opened", category: "service_request", source: "service_request", fieldPath: "srReopenedLabel", fieldType: "string", isActive: true, isSystem: true, order: 603 },
  { key: "sr_reopen_count", label: "Re-open Count", description: "Number of times the SR was re-opened", category: "service_request", source: "service_request", fieldPath: "srReopenCount", fieldType: "number", isActive: true, isSystem: true, order: 604 },
  { key: "sr_wip_committed_date", label: "WIP Committed Date", description: "Committed closure date set during WIP", category: "service_request", source: "service_request", fieldPath: "srWipCommittedDate", fieldType: "date", isActive: true, isSystem: true, order: 605 },
  { key: "sr_wip_revision_count", label: "WIP Revisions", description: "Number of committed-date revisions", category: "service_request", source: "service_request", fieldPath: "srWipRevisionCount", fieldType: "number", isActive: true, isSystem: true, order: 606 },
  { key: "sr_parent_satisfied", label: "Parent Satisfaction", description: "Parent closure feedback (Satisfied / Not satisfied)", category: "service_request", source: "service_request", fieldPath: "srParentSatisfiedLabel", fieldType: "string", isActive: true, isSystem: true, order: 607 },
  { key: "sr_auto_closed", label: "Auto-closed?", description: "Whether an auto-close rule closed the SR on creation", category: "service_request", source: "service_request", fieldPath: "srAutoClosedLabel", fieldType: "string", isActive: true, isSystem: true, order: 608 },
  { key: "sr_sla_source", label: "SLA Source", description: "Which SLA drove the TAT (category / priority / default)", category: "service_request", source: "service_request", fieldPath: "srSlaSource", fieldType: "string", isActive: true, isSystem: true, order: 609 },

  // Identity & classification
  { key: "sr_status_name", label: "Status (configured)", description: "Status name as configured for the project (status master)", category: "service_request", source: "service_request", fieldPath: "srStatusName", fieldType: "string", isActive: true, isSystem: true, order: 610 },
  { key: "sr_request_type", label: "PSR Request Type", description: "OCR (on-call resolution) or SR (full workflow)", category: "service_request", source: "service_request", fieldPath: "srRequestType", fieldType: "string", isActive: true, isSystem: true, order: 611 },
  { key: "sr_mode_of_contact", label: "Mode of Contact", description: "How the requester made contact (telephone / walk-in / email / portal / IVR / digital)", category: "service_request", source: "service_request", fieldPath: "srModeOfContact", fieldType: "string", isActive: true, isSystem: true, order: 612 },
  { key: "sr_source_label", label: "Channel", description: "Channel the request came in on", category: "service_request", source: "service_request", fieldPath: "srSourceLabel", fieldType: "string", isActive: true, isSystem: true, order: 613 },
  { key: "sr_linked_psr", label: "Linked PSR #", description: "For an ISR, the parent PSR it was raised from", category: "service_request", source: "service_request", fieldPath: "srLinkedPsrNumber", fieldType: "string", isActive: true, isSystem: true, order: 614 },
  { key: "sr_linked_isr_count", label: "Linked ISR Count", description: "How many ISRs were raised from this PSR", category: "service_request", source: "service_request", fieldPath: "srLinkedIsrCount", fieldType: "number", isActive: true, isSystem: true, order: 615 },
  { key: "sr_merged", label: "Merged Away?", description: "Whether this request was merged into another", category: "service_request", source: "service_request", fieldPath: "srMergedLabel", fieldType: "string", isActive: true, isSystem: true, order: 616 },
  { key: "sr_merged_into", label: "Merged Into #", description: "The request this one was merged into", category: "service_request", source: "service_request", fieldPath: "srMergedIntoNumber", fieldType: "string", isActive: true, isSystem: true, order: 617 },
  { key: "sr_merged_count", label: "Merged-in Count", description: "How many requests were merged into this one", category: "service_request", source: "service_request", fieldPath: "srMergedCount", fieldType: "number", isActive: true, isSystem: true, order: 618 },
  { key: "sr_watcher_count", label: "Watchers (CC)", description: "Number of people copied on the request", category: "service_request", source: "service_request", fieldPath: "srWatcherCount", fieldType: "number", isActive: true, isSystem: true, order: 619 },

  // Requester / beneficiary
  { key: "sr_requested_by_name", label: "Requester Name", description: "Who the request was raised for (parent or staff)", category: "service_request", source: "service_request", fieldPath: "srRequestedByName", fieldType: "string", isActive: true, isSystem: true, order: 620 },
  { key: "sr_requested_by_mobile", label: "Requester Mobile", description: "Requester mobile number", category: "service_request", source: "service_request", fieldPath: "srRequestedByMobile", fieldType: "string", isActive: true, isSystem: true, order: 621 },
  { key: "sr_requested_by_email", label: "Requester Email", description: "Requester email", category: "service_request", source: "service_request", fieldPath: "srRequestedByEmail", fieldType: "string", isActive: true, isSystem: true, order: 622 },
  { key: "sr_requested_by_type", label: "Requester Type", description: "Parent or staff", category: "service_request", source: "service_request", fieldPath: "srRequestedByType", fieldType: "string", isActive: true, isSystem: true, order: 623 },
  { key: "sr_student_count", label: "Students on Request", description: "How many children the request covers", category: "service_request", source: "service_request", fieldPath: "srStudentCount", fieldType: "number", isActive: true, isSystem: true, order: 624 },
  { key: "sr_student_names", label: "Student(s)", description: "Names of the children on the request", category: "service_request", source: "service_request", fieldPath: "srStudentNames", fieldType: "string", isActive: true, isSystem: true, order: 625 },

  // WIP commitment
  { key: "sr_wip_first_committed_date", label: "First Committed Date", description: "The first date committed to on this request", category: "service_request", source: "service_request", fieldPath: "srWipFirstCommittedDate", fieldType: "date", isActive: true, isSystem: true, order: 630 },
  { key: "sr_wip_last_set_by", label: "Committed Date Set By", description: "Who set the latest committed date", category: "service_request", source: "service_request", fieldPath: "srWipLastSetByName", fieldType: "string", isActive: true, isSystem: true, order: 631 },
  { key: "sr_wip_last_set_at", label: "Committed Date Set At", description: "When the latest committed date was set", category: "service_request", source: "service_request", fieldPath: "srWipLastSetAt", fieldType: "date", isActive: true, isSystem: true, order: 632 },
  { key: "sr_wip_last_reason", label: "Committed Date Reason", description: "Reason given with the latest committed date", category: "service_request", source: "service_request", fieldPath: "srWipLastReason", fieldType: "string", isActive: true, isSystem: true, order: 633 },
  { key: "sr_wip_reminder_sent_at", label: "WIP Reminder Sent At", description: "When the committed-date reminder went out", category: "service_request", source: "service_request", fieldPath: "srWipReminderSentAt", fieldType: "date", isActive: true, isSystem: true, order: 634 },
  { key: "sr_wip_escalated_at", label: "WIP Escalated At", description: "When the expired committed date triggered escalation", category: "service_request", source: "service_request", fieldPath: "srWipEscalatedAt", fieldType: "date", isActive: true, isSystem: true, order: 635 },
  { key: "sr_wip_expired", label: "Committed Date Expired?", description: "Committed date has passed and the request is still open", category: "service_request", source: "service_request", fieldPath: "srWipExpiredLabel", fieldType: "string", isActive: true, isSystem: true, order: 636 },
  { key: "sr_wip_commit_days", label: "Days Committed", description: "Days between raising the request and the committed date", category: "service_request", source: "service_request", fieldPath: "srWipCommitDays", fieldType: "number", isActive: true, isSystem: true, order: 637 },
  { key: "sr_wip_met", label: "Committed Date Met?", description: "Whether the request closed on or before its committed date", category: "service_request", source: "service_request", fieldPath: "srWipMetLabel", fieldType: "string", isActive: true, isSystem: true, order: 638 },
  { key: "sr_wip_overdue_hrs", label: "Committed Date Overdue (hrs)", description: "Hours past the committed date (to closure, or now if still open)", category: "service_request", source: "service_request", fieldPath: "srWipOverdueHrs", fieldType: "number", isActive: true, isSystem: true, order: 639 },

  // SLA hold (a status configured to pause the clock)
  { key: "sr_sla_on_hold", label: "SLA On Hold?", description: "Whether the SLA clock is currently held", category: "service_request", source: "service_request", fieldPath: "srSlaOnHoldLabel", fieldType: "string", isActive: true, isSystem: true, order: 640 },
  { key: "sr_sla_paused_at", label: "SLA Held Since", description: "When the SLA clock was held", category: "service_request", source: "service_request", fieldPath: "srSlaPausedAt", fieldType: "date", isActive: true, isSystem: true, order: 641 },
  { key: "sr_sla_resume_at", label: "SLA Resumes At", description: "When the held clock is due to start again", category: "service_request", source: "service_request", fieldPath: "srSlaResumeAt", fieldType: "date", isActive: true, isSystem: true, order: 642 },
  { key: "sr_sla_hold_hrs", label: "SLA Held (hrs)", description: "Total hours the SLA clock has been held", category: "service_request", source: "service_request", fieldPath: "srSlaHoldHrs", fieldType: "number", isActive: true, isSystem: true, order: 643 },

  // Lifecycle timings
  { key: "sr_age_days", label: "Age (days)", description: "Days since the request was raised (to closure, or now if open)", category: "service_request", source: "service_request", fieldPath: "srAgeDays", fieldType: "number", isActive: true, isSystem: true, order: 650 },
  { key: "sr_time_to_resolve_hrs", label: "Time to Resolve (hrs)", description: "Hours from raising to resolution", category: "service_request", source: "service_request", fieldPath: "srTimeToResolveHrs", fieldType: "number", isActive: true, isSystem: true, order: 651 },
  { key: "sr_time_to_close_hrs", label: "Time to Close (hrs)", description: "Hours from raising to closure", category: "service_request", source: "service_request", fieldPath: "srTimeToCloseHrs", fieldType: "number", isActive: true, isSystem: true, order: 652 },
  { key: "sr_status_change_count", label: "Status Changes", description: "How many times the status changed", category: "service_request", source: "service_request", fieldPath: "srStatusChangeCount", fieldType: "number", isActive: true, isSystem: true, order: 653 },
  { key: "sr_last_status_change_at", label: "Last Status Change", description: "When the status last changed", category: "service_request", source: "service_request", fieldPath: "srLastStatusChangeAt", fieldType: "date", isActive: true, isSystem: true, order: 654 },
  { key: "sr_attachment_count", label: "Attachments", description: "Number of files on the request", category: "service_request", source: "service_request", fieldPath: "srAttachmentCount", fieldType: "number", isActive: true, isSystem: true, order: 655 },
  { key: "sr_followup_count", label: "Follow-ups", description: "Number of follow-up notes on the request", category: "service_request", source: "service_request", fieldPath: "srFollowUpCount", fieldType: "number", isActive: true, isSystem: true, order: 656 },

  // Re-open / cancellation actors
  { key: "sr_reopened_by", label: "Re-opened By", description: "Who re-opened the request last", category: "service_request", source: "service_request", fieldPath: "srReopenedByName", fieldType: "string", isActive: true, isSystem: true, order: 660 },
  { key: "sr_reopened_at", label: "Re-opened At", description: "When the request was last re-opened", category: "service_request", source: "service_request", fieldPath: "srReopenedAt", fieldType: "date", isActive: true, isSystem: true, order: 661 },
  { key: "sr_cancelled_by", label: "Cancelled By", description: "Who cancelled the request", category: "service_request", source: "service_request", fieldPath: "srCancelledByName", fieldType: "string", isActive: true, isSystem: true, order: 662 },
  { key: "sr_cancelled_at", label: "Cancelled At", description: "When the request was cancelled", category: "service_request", source: "service_request", fieldPath: "srCancelledAt", fieldType: "date", isActive: true, isSystem: true, order: 663 },
  { key: "sr_replacement_ticket", label: "Replacement #", description: "Replacement request raised when this one was cancelled", category: "service_request", source: "service_request", fieldPath: "srReplacementNumber", fieldType: "string", isActive: true, isSystem: true, order: 664 },

  // Parent closure and PSL satisfaction call
  { key: "sr_parent_closed_at", label: "Parent Closed At", description: "When the parent confirmed closure", category: "service_request", source: "service_request", fieldPath: "srParentClosedAt", fieldType: "date", isActive: true, isSystem: true, order: 670 },
  { key: "sr_parent_comments", label: "Parent Closure Comments", description: "What the parent said on closure", category: "service_request", source: "service_request", fieldPath: "srParentComments", fieldType: "string", isActive: true, isSystem: true, order: 671 },
  { key: "sr_psl_spoken", label: "PSL Spoke to Parent?", description: "Whether the PSL reached the parent", category: "service_request", source: "service_request", fieldPath: "srPslSpokenLabel", fieldType: "string", isActive: true, isSystem: true, order: 672 },
  { key: "sr_psl_parent_satisfied", label: "PSL: Parent Satisfied?", description: "Outcome of the PSL satisfaction call", category: "service_request", source: "service_request", fieldPath: "srPslSatisfiedLabel", fieldType: "string", isActive: true, isSystem: true, order: 673 },
  { key: "sr_psl_called_by", label: "PSL Called By", description: "Who made the satisfaction call", category: "service_request", source: "service_request", fieldPath: "srPslCalledByName", fieldType: "string", isActive: true, isSystem: true, order: 674 },
  { key: "sr_psl_called_at", label: "PSL Called At", description: "When the satisfaction call was made", category: "service_request", source: "service_request", fieldPath: "srPslCalledAt", fieldType: "date", isActive: true, isSystem: true, order: 675 },
  { key: "sr_psl_comments", label: "PSL Comments", description: "Notes from the satisfaction call", category: "service_request", source: "service_request", fieldPath: "srPslComments", fieldType: "string", isActive: true, isSystem: true, order: 676 },

  // Hand-over: delegation and reassignment
  { key: "sr_delegated", label: "Delegated?", description: "Whether the request is currently delegated", category: "service_request", source: "service_request", fieldPath: "srDelegatedLabel", fieldType: "string", isActive: true, isSystem: true, order: 680 },
  { key: "sr_delegated_to", label: "Delegated To", description: "Who is covering the request", category: "service_request", source: "service_request", fieldPath: "srDelegatedToName", fieldType: "string", isActive: true, isSystem: true, order: 681 },
  { key: "sr_delegated_by", label: "Delegated By", description: "Who delegated it", category: "service_request", source: "service_request", fieldPath: "srDelegatedByName", fieldType: "string", isActive: true, isSystem: true, order: 682 },
  { key: "sr_delegated_at", label: "Delegated At", description: "When it was delegated", category: "service_request", source: "service_request", fieldPath: "srDelegatedAt", fieldType: "date", isActive: true, isSystem: true, order: 683 },
  { key: "sr_delegation_reason", label: "Delegation Reason", description: "Why it was delegated", category: "service_request", source: "service_request", fieldPath: "srDelegationReason", fieldType: "string", isActive: true, isSystem: true, order: 684 },
  { key: "sr_original_assignee", label: "Original Assignee", description: "Who held it before delegation", category: "service_request", source: "service_request", fieldPath: "srOriginalAssigneeName", fieldType: "string", isActive: true, isSystem: true, order: 685 },
  { key: "sr_reassign_count", label: "Reassignments", description: "How many times the request changed hands", category: "service_request", source: "service_request", fieldPath: "srReassignCount", fieldType: "number", isActive: true, isSystem: true, order: 686 },

  // IVR CALL GROUP (source: call - CallIntake, the service request call inbox)
  { key: "call_received_at", label: "Received At", description: "When the call reached the helpdesk", category: "call", source: "call", fieldPath: "receivedAt", fieldType: "date", isActive: true, isSystem: true, order: 700 },
  { key: "call_type", label: "Call Type", description: "Answered or missed", category: "call", source: "call", fieldPath: "callTypeLabel", fieldType: "string", isActive: true, isSystem: true, order: 701 },
  { key: "call_direction", label: "Direction", description: "Inbound or outbound", category: "call", source: "call", fieldPath: "directionLabel", fieldType: "string", isActive: true, isSystem: true, order: 702 },
  { key: "call_caller_name", label: "Caller Name", description: "Name of the caller, where known", category: "call", source: "call", fieldPath: "callerName", fieldType: "string", isActive: true, isSystem: true, order: 703 },
  { key: "call_caller_mobile", label: "Caller Mobile", description: "Number the call came from", category: "call", source: "call", fieldPath: "callerMobile", fieldType: "string", isActive: true, isSystem: true, order: 704 },
  { key: "call_did_number", label: "DID Number", description: "The number that was dialled", category: "call", source: "call", fieldPath: "callToNumber", fieldType: "string", isActive: true, isSystem: true, order: 705 },
  { key: "call_did_label", label: "DID Label", description: "Friendly name of the dialled number", category: "call", source: "call", fieldPath: "didLabel", fieldType: "string", isActive: true, isSystem: true, order: 706 },
  { key: "call_school", label: "School", description: "School named on the call", category: "call", source: "call", fieldPath: "schoolName", fieldType: "string", isActive: true, isSystem: true, order: 707 },
  { key: "call_duration_secs", label: "Duration (secs)", description: "Call duration in seconds", category: "call", source: "call", fieldPath: "durationSeconds", fieldType: "number", isActive: true, isSystem: true, order: 708 },
  { key: "call_start_at", label: "Call Start", description: "When the call started", category: "call", source: "call", fieldPath: "startStamp", fieldType: "date", isActive: true, isSystem: true, order: 709 },
  { key: "call_answer_at", label: "Answered At", description: "When the call was answered", category: "call", source: "call", fieldPath: "answerStamp", fieldType: "date", isActive: true, isSystem: true, order: 710 },
  { key: "call_end_at", label: "Call End", description: "When the call ended", category: "call", source: "call", fieldPath: "endStamp", fieldType: "date", isActive: true, isSystem: true, order: 711 },
  { key: "call_answered_agent", label: "Answered By", description: "Agent who answered on the IVR", category: "call", source: "call", fieldPath: "answeredAgentName", fieldType: "string", isActive: true, isSystem: true, order: 712 },
  { key: "call_assigned_to", label: "Assigned To", description: "Agent the call was assigned to for follow-up", category: "call", source: "call", fieldPath: "assignedToName", fieldType: "string", isActive: true, isSystem: true, order: 713 },
  { key: "call_assignment_status", label: "Assignment Status", description: "Assigned, or left unassigned because no agent was free", category: "call", source: "call", fieldPath: "assignmentStatus", fieldType: "string", isActive: true, isSystem: true, order: 714 },
  { key: "call_status", label: "Call Status", description: "New / assigned / converted / junk", category: "call", source: "call", fieldPath: "callStatus", fieldType: "string", isActive: true, isSystem: true, order: 715 },
  { key: "call_open_closed", label: "Open or Closed", description: "Whether the call record is still open", category: "call", source: "call", fieldPath: "statusLabel", fieldType: "string", isActive: true, isSystem: true, order: 716 },
  { key: "call_registered", label: "Registered Caller?", description: "Whether the caller matched a registered student or parent", category: "call", source: "call", fieldPath: "registeredLabel", fieldType: "string", isActive: true, isSystem: true, order: 717 },
  { key: "call_requester_type", label: "Requester Type", description: "How the caller was identified", category: "call", source: "call", fieldPath: "requesterType", fieldType: "string", isActive: true, isSystem: true, order: 718 },
  { key: "call_student_count", label: "Students Matched", description: "How many students matched the caller", category: "call", source: "call", fieldPath: "studentCount", fieldType: "number", isActive: true, isSystem: true, order: 719 },
  { key: "call_matched_by", label: "Matched By", description: "What the caller was matched on", category: "call", source: "call", fieldPath: "matchedBy", fieldType: "string", isActive: true, isSystem: true, order: 720 },
  { key: "call_converted_ticket", label: "Converted Ticket #", description: "Service request raised from this call", category: "call", source: "call", fieldPath: "convertedTicketNumber", fieldType: "string", isActive: true, isSystem: true, order: 721 },
  { key: "call_converted_at", label: "Converted At", description: "When the call became a service request", category: "call", source: "call", fieldPath: "convertedAt", fieldType: "date", isActive: true, isSystem: true, order: 722 },
  { key: "call_converted_count", label: "Requests Raised", description: "How many requests were raised from this call", category: "call", source: "call", fieldPath: "convertedCount", fieldType: "number", isActive: true, isSystem: true, order: 723 },
  { key: "call_resolved_on_call", label: "Resolved on Call?", description: "Handled on the call without raising a request", category: "call", source: "call", fieldPath: "resolvedOnCallLabel", fieldType: "string", isActive: true, isSystem: true, order: 724 },
  { key: "call_recording_url", label: "Recording URL", description: "Recording of the inbound call", category: "call", source: "call", fieldPath: "recordingUrl", fieldType: "string", isActive: true, isSystem: true, order: 725 },
  { key: "call_voice_note_url", label: "Voice Note URL", description: "Voicemail left by the caller", category: "call", source: "call", fieldPath: "voiceNoteUrl", fieldType: "string", isActive: true, isSystem: true, order: 726 },
  { key: "call_remark", label: "Remark", description: "Agent remark on the call", category: "call", source: "call", fieldPath: "remark", fieldType: "string", isActive: true, isSystem: true, order: 727 },
  { key: "call_followup_count", label: "Follow-up Attempts", description: "Call-back attempts logged against this call", category: "call", source: "call", fieldPath: "followUpCount", fieldType: "number", isActive: true, isSystem: true, order: 728 },
  { key: "call_last_followup_outcome", label: "Last Follow-up Outcome", description: "Outcome of the last call-back attempt", category: "call", source: "call", fieldPath: "lastFollowUpOutcome", fieldType: "string", isActive: true, isSystem: true, order: 729 },
  { key: "call_callback_at", label: "Call-back Due", description: "When the next call-back is due", category: "call", source: "call", fieldPath: "callbackAt", fieldType: "date", isActive: true, isSystem: true, order: 730 },
  { key: "call_outbound_count", label: "Outbound Calls", description: "Click-to-call attempts made from the inbox", category: "call", source: "call", fieldPath: "outboundCount", fieldType: "number", isActive: true, isSystem: true, order: 731 },
  { key: "call_last_outbound_status", label: "Last Outbound Status", description: "Result of the last outbound attempt", category: "call", source: "call", fieldPath: "lastOutboundStatus", fieldType: "string", isActive: true, isSystem: true, order: 732 },
  { key: "call_last_outbound_at", label: "Last Outbound At", description: "When the last outbound attempt was made", category: "call", source: "call", fieldPath: "lastOutboundAt", fieldType: "date", isActive: true, isSystem: true, order: 733 },
  { key: "call_comment_count", label: "Comments", description: "Notes added against the call", category: "call", source: "call", fieldPath: "commentCount", fieldType: "number", isActive: true, isSystem: true, order: 734 },
  { key: "call_provider_status", label: "Provider Status", description: "Status reported by the telephony provider", category: "call", source: "call", fieldPath: "providerCallStatus", fieldType: "string", isActive: true, isSystem: true, order: 735 },
  { key: "call_external_id", label: "Provider Call ID", description: "The provider id for the call", category: "call", source: "call", fieldPath: "externalId", fieldType: "string", isActive: true, isSystem: true, order: 736 },
  { key: "call_project", label: "Project", description: "Project the call belongs to", category: "call", source: "call", fieldPath: "projectName", fieldType: "string", isActive: true, isSystem: true, order: 737 },

  // Earlier names, kept so existing saved reports keep working.
  { key: "sr_number", label: "Request #", description: "Service request number", category: "service_request", source: "service_request", fieldPath: "ticketNumber", fieldType: "string", isActive: true, isSystem: true, order: 690 },
  { key: "sr_type", label: "Type", description: "PSR / ISR", category: "service_request", source: "service_request", fieldPath: "interactionTypeLabel", fieldType: "string", isActive: true, isSystem: true, order: 691 },
  { key: "sr_subject", label: "Subject", description: "What the request is about", category: "service_request", source: "service_request", fieldPath: "subject", fieldType: "string", isActive: true, isSystem: true, order: 692 },
  { key: "sr_status", label: "Status", description: "Current status", category: "service_request", source: "service_request", fieldPath: "statusLabel", fieldType: "string", isActive: true, isSystem: true, order: 693 },
  { key: "sr_category", label: "Category", description: "Category the request is filed under", category: "service_request", source: "service_request", fieldPath: "categoryDisplay", fieldType: "string", isActive: true, isSystem: true, order: 694 },
  { key: "sr_mode", label: "Submitted Via", description: "How the request was submitted", category: "service_request", source: "service_request", fieldPath: "submissionSource", fieldType: "string", isActive: true, isSystem: true, order: 695 },
  { key: "sr_assigned_to", label: "Assigned To", description: "Who is working the request", category: "service_request", source: "service_request", fieldPath: "assignedToName", fieldType: "string", isActive: true, isSystem: true, order: 696 },
  { key: "sr_requester", label: "Raised By", description: "Who raised the request", category: "service_request", source: "service_request", fieldPath: "createdByName", fieldType: "string", isActive: true, isSystem: true, order: 697 },
  { key: "sr_created_at", label: "Raised At", description: "When the request was raised", category: "service_request", source: "service_request", fieldPath: "createdAt", fieldType: "date", isActive: true, isSystem: true, order: 698 },
  { key: "sr_resolved_at", label: "Resolved At", description: "When the request was resolved", category: "service_request", source: "service_request", fieldPath: "resolvedAt", fieldType: "date", isActive: true, isSystem: true, order: 699 },
  { key: "sr_closed_at", label: "Closed At", description: "When the request was closed", category: "service_request", source: "service_request", fieldPath: "closedAt", fieldType: "date", isActive: true, isSystem: true, order: 700 },
  { key: "sr_sla_status", label: "SLA Status", description: "Within SLA or breached", category: "service_request", source: "service_request", fieldPath: "slaStatus", fieldType: "string", isActive: true, isSystem: true, order: 701 },
  { key: "sr_project", label: "Project", description: "Project the request belongs to", category: "service_request", source: "service_request", fieldPath: "projectName", fieldType: "string", isActive: true, isSystem: true, order: 702 },
  { key: "sr_satisfied", label: "Parent Satisfied?", description: "Parent closure feedback", category: "service_request", source: "service_request", fieldPath: "srParentSatisfiedLabel", fieldType: "string", isActive: true, isSystem: true, order: 703 },
  { key: "sr_rating", label: "Feedback Rating", description: "CSAT rating left on the request", category: "service_request", source: "service_request", fieldPath: "csatScore", fieldType: "number", isActive: true, isSystem: true, order: 704 },
  { key: "call_number", label: "Caller Number", description: "Number the call came from", category: "call", source: "call", fieldPath: "callerMobile", fieldType: "string", isActive: true, isSystem: true, order: 750 },
  { key: "call_disposition", label: "Disposition", description: "Status the telephony provider reported", category: "call", source: "call", fieldPath: "providerCallStatus", fieldType: "string", isActive: true, isSystem: true, order: 751 },
  { key: "call_duration", label: "Duration (secs)", description: "Call duration in seconds", category: "call", source: "call", fieldPath: "durationSeconds", fieldType: "number", isActive: true, isSystem: true, order: 752 },
  { key: "call_agent", label: "Agent", description: "Agent the call sits with", category: "call", source: "call", fieldPath: "assignedToName", fieldType: "string", isActive: true, isSystem: true, order: 753 },
  { key: "call_linked_count", label: "Requests Raised", description: "Requests raised from this call", category: "call", source: "call", fieldPath: "convertedCount", fieldType: "number", isActive: true, isSystem: true, order: 754 },
  { key: "call_created_at", label: "Received At", description: "When the call reached the helpdesk", category: "call", source: "call", fieldPath: "receivedAt", fieldType: "date", isActive: true, isSystem: true, order: 755 },

  // The everyday columns, offered on the Service Requests source too.
  { key: "sr_priority", label: "Priority", description: "Priority of the request", category: "service_request", source: "service_request", fieldPath: "priority", fieldType: "string", isActive: true, isSystem: true, order: 760 },
  { key: "sr_description", label: "Description", description: "What the requester described", category: "service_request", source: "service_request", fieldPath: "description", fieldType: "string", isActive: true, isSystem: true, order: 761 },
  { key: "sr_tags", label: "Tags", description: "Tags on the request", category: "service_request", source: "service_request", fieldPath: "tags", fieldType: "array", isActive: true, isSystem: true, order: 762 },
  { key: "sr_center", label: "Offline Center", description: "Centre the request belongs to", category: "service_request", source: "service_request", fieldPath: "centerName", fieldType: "string", isActive: true, isSystem: true, order: 763 },
  { key: "sr_district", label: "District", description: "District of the centre", category: "service_request", source: "service_request", fieldPath: "centerDistrict", fieldType: "string", isActive: true, isSystem: true, order: 764 },
  { key: "sr_mobile", label: "Mobile", description: "Normalised mobile on the request", category: "service_request", source: "service_request", fieldPath: "mobile", fieldType: "string", isActive: true, isSystem: true, order: 765 },
  { key: "sr_registered", label: "Registered Requester?", description: "Whether the requester is a registered user", category: "service_request", source: "service_request", fieldPath: "srRegisteredLabel", fieldType: "string", isActive: true, isSystem: true, order: 766 },
  { key: "sr_submission_type", label: "Submission Type", description: "Online or offline submission", category: "service_request", source: "service_request", fieldPath: "srSubmissionType", fieldType: "string", isActive: true, isSystem: true, order: 767 },
  { key: "sr_student_name", label: "Student Name", description: "Student named on the request", category: "service_request", source: "service_request", fieldPath: "srStudentName", fieldType: "string", isActive: true, isSystem: true, order: 768 },
  { key: "sr_requester_email", label: "Raised By Email", description: "Email of whoever raised it", category: "service_request", source: "service_request", fieldPath: "createdByEmail", fieldType: "string", isActive: true, isSystem: true, order: 769 },
  { key: "sr_requester_department", label: "Raised By Department", description: "Department of whoever raised it", category: "service_request", source: "service_request", fieldPath: "createdByDepartment", fieldType: "string", isActive: true, isSystem: true, order: 770 },
  { key: "sr_requester_unique_id", label: "Raised By ID", description: "Unique id of whoever raised it", category: "service_request", source: "service_request", fieldPath: "createdByUniqueId", fieldType: "string", isActive: true, isSystem: true, order: 771 },
  { key: "sr_assigned_role", label: "Assignee Role", description: "Role of the person working it", category: "service_request", source: "service_request", fieldPath: "assignedToRoleName", fieldType: "string", isActive: true, isSystem: true, order: 772 },
  { key: "sr_assigned_via", label: "Assigned Via", description: "What put it with its current assignee", category: "service_request", source: "service_request", fieldPath: "assignedVia", fieldType: "string", isActive: true, isSystem: true, order: 773 },
  { key: "sr_assignment_attempts", label: "Assignment Attempts", description: "How many times auto-assignment tried", category: "service_request", source: "service_request", fieldPath: "assignmentAttempts", fieldType: "number", isActive: true, isSystem: true, order: 774 },
  { key: "sr_updated_at", label: "Last Updated", description: "When the request last changed", category: "service_request", source: "service_request", fieldPath: "updatedAt", fieldType: "date", isActive: true, isSystem: true, order: 775 },
  { key: "sr_unread_by_agent", label: "Unread by Agent?", description: "A reply is waiting that no agent has opened", category: "service_request", source: "service_request", fieldPath: "srUnreadLabel", fieldType: "string", isActive: true, isSystem: true, order: 776 },
  { key: "sr_watchers", label: "Watchers (CC)", description: "People copied on the request", category: "service_request", source: "service_request", fieldPath: "srWatcherNames", fieldType: "string", isActive: true, isSystem: true, order: 777 },
  { key: "sr_internal_note_count", label: "Internal Notes", description: "Internal notes on the request", category: "service_request", source: "service_request", fieldPath: "srInternalNoteCount", fieldType: "number", isActive: true, isSystem: true, order: 778 },
  { key: "sr_thread_count", label: "Email Thread Messages", description: "Messages in the request's email thread", category: "service_request", source: "service_request", fieldPath: "srThreadCount", fieldType: "number", isActive: true, isSystem: true, order: 779 },
  { key: "sr_feedback_comment", label: "Feedback Comment", description: "What the requester said in feedback", category: "service_request", source: "service_request", fieldPath: "feedbackComment", fieldType: "string", isActive: true, isSystem: true, order: 780 },

  // SLA and escalation, on the service request source.
  { key: "sr_sla_due_at", label: "SLA Due At", description: "When the SLA expires", category: "service_request", source: "service_request", fieldPath: "slaDueAt", fieldType: "date", isActive: true, isSystem: true, order: 781 },
  { key: "sr_sla_breached_at", label: "SLA Breached At", description: "When the SLA was breached", category: "service_request", source: "service_request", fieldPath: "slaBreachedAt", fieldType: "date", isActive: true, isSystem: true, order: 782 },
  { key: "sr_sla_breached", label: "SLA Breached?", description: "Whether the SLA has been breached", category: "service_request", source: "service_request", fieldPath: "srSlaBreachedLabel", fieldType: "string", isActive: true, isSystem: true, order: 783 },
  { key: "sr_first_responded_at", label: "First Response At", description: "When the requester first got a reply", category: "service_request", source: "service_request", fieldPath: "firstRespondedAt", fieldType: "date", isActive: true, isSystem: true, order: 784 },
  { key: "sr_first_response_hrs", label: "Time to First Response (hrs)", description: "Hours from raising to the first reply", category: "service_request", source: "service_request", fieldPath: "srFirstResponseHrs", fieldType: "number", isActive: true, isSystem: true, order: 785 },
  { key: "sr_escalation_level", label: "Escalation Level", description: "Current escalation level number", category: "service_request", source: "service_request", fieldPath: "currentEscalationLevelNumber", fieldType: "number", isActive: true, isSystem: true, order: 786 },
  { key: "sr_escalation_count", label: "Escalations", description: "How many times it was escalated", category: "service_request", source: "service_request", fieldPath: "escalationCount", fieldType: "number", isActive: true, isSystem: true, order: 787 },
  { key: "sr_last_escalated_at", label: "Last Escalated At", description: "When it was last escalated", category: "service_request", source: "service_request", fieldPath: "srLastEscalatedAt", fieldType: "date", isActive: true, isSystem: true, order: 788 },
  { key: "sr_merged_at", label: "Merged At", description: "When the merge happened", category: "service_request", source: "service_request", fieldPath: "mergedAt", fieldType: "date", isActive: true, isSystem: true, order: 789 },
  { key: "sr_wip_all_committed_dates", label: "All Committed Dates", description: "Every date committed on this request, in order", category: "service_request", source: "service_request", fieldPath: "srWipAllCommittedDates", fieldType: "string", isActive: true, isSystem: true, order: 790 },
  { key: "sr_schedule_dispatch_date", label: "Scheduled Dispatch", description: "Date the request was scheduled to go out", category: "service_request", source: "service_request", fieldPath: "srScheduleDispatchDate", fieldType: "date", isActive: true, isSystem: true, order: 791 },
  { key: "sr_created_by_re", label: "Raised by RE?", description: "Raised on the requester's behalf by a relationship executive", category: "service_request", source: "service_request", fieldPath: "srCreatedByReLabel", fieldType: "string", isActive: true, isSystem: true, order: 792 },
  { key: "sr_assignment_rule", label: "Assignment Rule", description: "Rule that decided the first assignee", category: "service_request", source: "service_request", fieldPath: "srAssignmentRule", fieldType: "string", isActive: true, isSystem: true, order: 793 },

  // Call inbox: the call-back ladder, notes and outbound attempts.
  { key: "call_provider", label: "Provider", description: "Telephony provider the call came from", category: "call", source: "call", fieldPath: "provider", fieldType: "string", isActive: true, isSystem: true, order: 800 },
  { key: "call_digits_dialed", label: "IVR Keys Pressed", description: "Digits the caller pressed in the IVR menu", category: "call", source: "call", fieldPath: "digitsDialedText", fieldType: "string", isActive: true, isSystem: true, order: 801 },
  { key: "call_answered_agent_number", label: "Answered On Number", description: "Extension or number that took the call", category: "call", source: "call", fieldPath: "answeredAgentNumber", fieldType: "string", isActive: true, isSystem: true, order: 802 },
  { key: "call_assigned_bucket", label: "Assigned Bucket", description: "Queue the call was routed to", category: "call", source: "call", fieldPath: "assignedBucket", fieldType: "string", isActive: true, isSystem: true, order: 803 },
  { key: "call_original_provider_status", label: "Original Provider Status", description: "First status the provider reported", category: "call", source: "call", fieldPath: "originalProviderCallStatus", fieldType: "string", isActive: true, isSystem: true, order: 804 },
  { key: "call_callback_due_soon_at", label: "Call-back Turning Urgent", description: "When the pending call-back passes 80% of its TAT", category: "call", source: "call", fieldPath: "callbackDueSoonAt", fieldType: "date", isActive: true, isSystem: true, order: 805 },
  { key: "call_pending_followups", label: "Pending Call-backs", description: "Call-back steps still open", category: "call", source: "call", fieldPath: "pendingFollowUpCount", fieldType: "number", isActive: true, isSystem: true, order: 806 },
  { key: "call_last_followup_at", label: "Last Call-back Logged", description: "When the last call-back step was logged", category: "call", source: "call", fieldPath: "lastFollowUpAt", fieldType: "date", isActive: true, isSystem: true, order: 807 },
  { key: "call_wip_level", label: "Call-back Ladder Step", description: "Which step of the call-back ladder the call is on", category: "call", source: "call", fieldPath: "lastWipLevel", fieldType: "number", isActive: true, isSystem: true, order: 808 },
  { key: "call_wip_label", label: "Call-back Step Name", description: "Name of that ladder step", category: "call", source: "call", fieldPath: "lastWipLabel", fieldType: "string", isActive: true, isSystem: true, order: 809 },
  { key: "call_callback_tat_hours", label: "Call-back TAT (hrs)", description: "Hours promised by the current ladder step", category: "call", source: "call", fieldPath: "lastTatHours", fieldType: "number", isActive: true, isSystem: true, order: 810 },
  { key: "call_callback_requested_at", label: "Caller Asked to Be Called At", description: "Time the caller asked to be called back", category: "call", source: "call", fieldPath: "lastCallbackRequestedAt", fieldType: "date", isActive: true, isSystem: true, order: 811 },
  { key: "call_last_comment", label: "Last Note", description: "Most recent agent note on the call", category: "call", source: "call", fieldPath: "lastCommentText", fieldType: "string", isActive: true, isSystem: true, order: 812 },
  { key: "call_last_comment_by", label: "Last Note By", description: "Who wrote that note", category: "call", source: "call", fieldPath: "lastCommentBy", fieldType: "string", isActive: true, isSystem: true, order: 813 },
  { key: "call_last_comment_at", label: "Last Note At", description: "When that note was written", category: "call", source: "call", fieldPath: "lastCommentAt", fieldType: "date", isActive: true, isSystem: true, order: 814 },
  { key: "call_outbound_talk_secs", label: "Outbound Talk Time (secs)", description: "Total time spent on call-backs to this caller", category: "call", source: "call", fieldPath: "outboundTalkSeconds", fieldType: "number", isActive: true, isSystem: true, order: 815 },
  { key: "call_outbound_last_agent", label: "Last Call-back By", description: "Agent who placed the last outbound call", category: "call", source: "call", fieldPath: "lastOutboundAgent", fieldType: "string", isActive: true, isSystem: true, order: 816 },
  { key: "call_outbound_last_duration", label: "Last Call-back Duration (secs)", description: "How long the last outbound call lasted", category: "call", source: "call", fieldPath: "lastOutboundDuration", fieldType: "number", isActive: true, isSystem: true, order: 817 },
  { key: "call_outbound_last_recording", label: "Last Call-back Recording", description: "Recording of the last outbound call", category: "call", source: "call", fieldPath: "lastOutboundRecording", fieldType: "string", isActive: true, isSystem: true, order: 818 },
  { key: "call_converted_numbers", label: "Requests Raised (numbers)", description: "Every request raised from this call", category: "call", source: "call", fieldPath: "convertedNumbers", fieldType: "string", isActive: true, isSystem: true, order: 819 },

  // EMAIL INTAKE GROUP (source: email_intake - the SR email triage queue)
  { key: "ei_received_at", label: "Received At", description: "When the email arrived", category: "email_intake", source: "email_intake", fieldPath: "receivedAt", fieldType: "date", isActive: true, isSystem: true, order: 830 },
  { key: "ei_unique_id", label: "Intake ID", description: "Reference given to the email", category: "email_intake", source: "email_intake", fieldPath: "uniqueId", fieldType: "string", isActive: true, isSystem: true, order: 831 },
  { key: "ei_from_name", label: "From Name", description: "Who the email is from", category: "email_intake", source: "email_intake", fieldPath: "fromName", fieldType: "string", isActive: true, isSystem: true, order: 832 },
  { key: "ei_from_email", label: "From Email", description: "Address the email came from", category: "email_intake", source: "email_intake", fieldPath: "fromEmail", fieldType: "string", isActive: true, isSystem: true, order: 833 },
  { key: "ei_to_email", label: "To Address", description: "Helpdesk address that received it", category: "email_intake", source: "email_intake", fieldPath: "toEmail", fieldType: "string", isActive: true, isSystem: true, order: 834 },
  { key: "ei_subject", label: "Subject", description: "Subject line", category: "email_intake", source: "email_intake", fieldPath: "subject", fieldType: "string", isActive: true, isSystem: true, order: 835 },
  { key: "ei_sender_type", label: "Sender Type", description: "How the sender was identified", category: "email_intake", source: "email_intake", fieldPath: "senderType", fieldType: "string", isActive: true, isSystem: true, order: 836 },
  { key: "ei_sub_category", label: "Sub Category", description: "Sub category the email was filed under", category: "email_intake", source: "email_intake", fieldPath: "subCategory", fieldType: "string", isActive: true, isSystem: true, order: 837 },
  { key: "ei_status", label: "Status", description: "Where the email sits in triage", category: "email_intake", source: "email_intake", fieldPath: "status", fieldType: "string", isActive: true, isSystem: true, order: 838 },
  { key: "ei_assigned_to", label: "Assigned To", description: "Agent handling the email", category: "email_intake", source: "email_intake", fieldPath: "assignedToName", fieldType: "string", isActive: true, isSystem: true, order: 839 },
  { key: "ei_due_at", label: "TAT Due At", description: "When the triage TAT expires", category: "email_intake", source: "email_intake", fieldPath: "dueAt", fieldType: "date", isActive: true, isSystem: true, order: 840 },
  { key: "ei_overdue", label: "Past TAT?", description: "Still open after its TAT", category: "email_intake", source: "email_intake", fieldPath: "overdueLabel", fieldType: "string", isActive: true, isSystem: true, order: 841 },
  { key: "ei_escalation_level", label: "Escalation Level", description: "Escalation level reached", category: "email_intake", source: "email_intake", fieldPath: "escalationLevel", fieldType: "number", isActive: true, isSystem: true, order: 842 },
  { key: "ei_escalated_at", label: "Escalated At", description: "When it was escalated", category: "email_intake", source: "email_intake", fieldPath: "escalatedAt", fieldType: "date", isActive: true, isSystem: true, order: 843 },
  { key: "ei_closed_at", label: "Closed At", description: "When triage was finished", category: "email_intake", source: "email_intake", fieldPath: "closedAt", fieldType: "date", isActive: true, isSystem: true, order: 844 },
  { key: "ei_closed_by", label: "Closed By", description: "Who finished it", category: "email_intake", source: "email_intake", fieldPath: "closedByName", fieldType: "string", isActive: true, isSystem: true, order: 845 },
  { key: "ei_action_count", label: "Actions Taken", description: "How many actions were recorded", category: "email_intake", source: "email_intake", fieldPath: "actionCount", fieldType: "number", isActive: true, isSystem: true, order: 846 },
  { key: "ei_age_hrs", label: "Age (hrs)", description: "Hours since it arrived (to closure, or now)", category: "email_intake", source: "email_intake", fieldPath: "ageHrs", fieldType: "number", isActive: true, isSystem: true, order: 847 },
  { key: "ei_time_to_close_hrs", label: "Time to Close (hrs)", description: "Hours from arriving to being closed", category: "email_intake", source: "email_intake", fieldPath: "timeToCloseHrs", fieldType: "number", isActive: true, isSystem: true, order: 848 },
  { key: "ei_project", label: "Project", description: "Project the email belongs to", category: "email_intake", source: "email_intake", fieldPath: "projectName", fieldType: "string", isActive: true, isSystem: true, order: 849 },
];
