// Permission codes for RBAC
export const PERMISSION_CODES = {
  // Dashboard
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  DASHBOARD_VIEW_ANALYTICS: "DASHBOARD_VIEW_ANALYTICS",
  DASHBOARD_EXPORT: "DASHBOARD_EXPORT",

  // Project Management
  PROJECT_VIEW_ALL: "PROJECT_VIEW_ALL",
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_EDIT: "PROJECT_EDIT",
  PROJECT_DELETE: "PROJECT_DELETE",
  PROJECT_TOGGLE_STATUS: "PROJECT_TOGGLE_STATUS",
  PROJECT_MANAGE_SETTINGS: "PROJECT_MANAGE_SETTINGS",
  PROJECT_MANAGE_BRANDING: "PROJECT_MANAGE_BRANDING",
  PROJECT_MANAGE_URL: "PROJECT_MANAGE_URL",
  PROJECT_ASSIGN_USERS: "PROJECT_ASSIGN_USERS",

  // Tickets
  TICKET_VIEW_ALL: "TICKET_VIEW_ALL",
  TICKET_VIEW_OWN: "TICKET_VIEW_OWN",
  TICKET_CREATE: "TICKET_CREATE",
  TICKET_EDIT: "TICKET_EDIT",
  TICKET_DELETE: "TICKET_DELETE",
  TICKET_ASSIGN: "TICKET_ASSIGN",
  TICKET_REASSIGN: "TICKET_REASSIGN",
  TICKET_ESCALATE: "TICKET_ESCALATE",
  TICKET_CHANGE_STATUS: "TICKET_CHANGE_STATUS",
  TICKET_CHANGE_PRIORITY: "TICKET_CHANGE_PRIORITY",
  TICKET_CHANGE_CATEGORY: "TICKET_CHANGE_CATEGORY",
  TICKET_ADD_COMMENT: "TICKET_ADD_COMMENT",
  TICKET_EDIT_COMMENT: "TICKET_EDIT_COMMENT",
  TICKET_DELETE_COMMENT: "TICKET_DELETE_COMMENT",
  TICKET_ADD_ATTACHMENT: "TICKET_ADD_ATTACHMENT",
  TICKET_DELETE_ATTACHMENT: "TICKET_DELETE_ATTACHMENT",
  TICKET_MERGE: "TICKET_MERGE",
  TICKET_BULK_UPDATE: "TICKET_BULK_UPDATE",
  TICKET_EXPORT: "TICKET_EXPORT",
  TICKET_MODIFY_ANY: "TICKET_MODIFY_ANY",
  // Lifecycle actions shared by normal queries, ISRs and PSRs
  TICKET_REPLY: "TICKET_REPLY",
  TICKET_CLOSE: "TICKET_CLOSE",
  TICKET_REOPEN: "TICKET_REOPEN",
  TICKET_CANCEL: "TICKET_CANCEL",
  TICKET_DELEGATE: "TICKET_DELEGATE",
  TICKET_LINK: "TICKET_LINK",
  TICKET_CONFIG_MANAGE_TABLE_COLUMNS: "TICKET_CONFIG_MANAGE_TABLE_COLUMNS",

  // Offline Module
  OFFLINE_MODULE_ACCESS: "OFFLINE_MODULE_ACCESS",
  OFFLINE_STUDENT_REGISTER: "OFFLINE_STUDENT_REGISTER",
  OFFLINE_TICKET_CREATE: "OFFLINE_TICKET_CREATE",
  OFFLINE_TICKET_RESOLVE: "OFFLINE_TICKET_RESOLVE",
  OFFLINE_TICKET_ESCALATE: "OFFLINE_TICKET_ESCALATE",
  OFFLINE_STUDENT_VIEW: "OFFLINE_STUDENT_VIEW",
  OFFLINE_STUDENT_EDIT: "OFFLINE_STUDENT_EDIT",

  // User Management
  USER_VIEW_ALL: "USER_VIEW_ALL",
  USER_CREATE: "USER_CREATE",
  USER_EDIT: "USER_EDIT",
  USER_DELETE: "USER_DELETE",
  USER_TOGGLE_STATUS: "USER_TOGGLE_STATUS",
  USER_ASSIGN_ROLE: "USER_ASSIGN_ROLE",
  USER_RESET_PASSWORD: "USER_RESET_PASSWORD",
  USER_IMPORT: "USER_IMPORT",
  // Impersonation ("Login as user") — token-based, audited, DPDP compliant.
  // IMPERSONATE_USER: holder may log in as another (non-exempt) user.
  // IMPERSONATION_EXEMPT: a role holding this CANNOT be impersonated (assign to
  // Super Admin / Sub Admin). Configurable, never hardcoded by role name.
  IMPERSONATE_USER: "IMPERSONATE_USER",
  IMPERSONATION_EXEMPT: "IMPERSONATION_EXEMPT",

  // Reports
  REPORT_VIEW_TICKETS: "REPORT_VIEW_TICKETS",
  REPORT_VIEW_AGENT_PERFORMANCE: "REPORT_VIEW_AGENT_PERFORMANCE",
  REPORT_VIEW_CSAT: "REPORT_VIEW_CSAT",
  REPORT_VIEW_SLA: "REPORT_VIEW_SLA",
  REPORT_VIEW_QUERY: "REPORT_VIEW_QUERY",
  REPORT_VIEW_ASSET: "REPORT_VIEW_ASSET",
  REPORT_VIEW_EMPLOYEE: "REPORT_VIEW_EMPLOYEE",
  REPORT_EXPORT: "REPORT_EXPORT",
  REPORT_CREATE_CUSTOM: "REPORT_CREATE_CUSTOM",
  REPORT_SCHEDULE: "REPORT_SCHEDULE",

  // Form Builder
  FORM_VIEW: "FORM_VIEW",
  FORM_CREATE: "FORM_CREATE",
  FORM_EDIT: "FORM_EDIT",
  FORM_DELETE: "FORM_DELETE",
  FORM_ASSIGN_CONTEXT: "FORM_ASSIGN_CONTEXT",
  FORM_VIEW_AUDIT_LOGS: "FORM_VIEW_AUDIT_LOGS",

  // Email Integration
  EMAIL_CONFIG_VIEW: "EMAIL_CONFIG_VIEW",
  EMAIL_CONFIG_EDIT: "EMAIL_CONFIG_EDIT",
  EMAIL_CONFIG_TEST: "EMAIL_CONFIG_TEST",
  EMAIL_TRIGGER_MANAGE: "EMAIL_TRIGGER_MANAGE",

  // Service Request (PSR/ISR) — SR settings and channel-agent capabilities only.
  // Record-level actions on an ISR/PSR use the TICKET_* codes above: an SR is a
  // Ticket with an `interactionType`.
  SR_ACCESS: "SR_ACCESS",
  IVR_TAT_CONFIG: "IVR_TAT_CONFIG",
  IVR_CALLBACK_SET: "IVR_CALLBACK_SET",
  SR_CONFIG_MANAGE: "SR_CONFIG_MANAGE",
  SR_ASSIGN_EMAILS: "SR_ASSIGN_EMAILS",
  SR_OFFLINE_ENTRY: "SR_OFFLINE_ENTRY",
  SR_DISPLAY_TO_PARENT: "SR_DISPLAY_TO_PARENT",
  EMAIL_TRIAGE_ACCESS: "EMAIL_TRIAGE_ACCESS",
  EMAIL_TRIAGE_ALL: "EMAIL_TRIAGE_ALL",
  EMAIL_TRIAGE_CONVERT: "EMAIL_TRIAGE_CONVERT",
  EMAIL_TRIAGE_RESPOND: "EMAIL_TRIAGE_RESPOND",
  IVR_TRIAGE_ACCESS: "IVR_TRIAGE_ACCESS",
  IVR_TRIAGE_CONVERT: "IVR_TRIAGE_CONVERT",
  IVR_AGENT_MANAGE: "IVR_AGENT_MANAGE",

  // Asset Management
  ASSET_VIEW: "ASSET_VIEW",
  ASSET_CREATE: "ASSET_CREATE",
  ASSET_EDIT: "ASSET_EDIT",
  ASSET_DELETE: "ASSET_DELETE",
  ASSET_MANAGE: "ASSET_MANAGE",
  ASSET_MAP_TO_CENTER: "ASSET_MAP_TO_CENTER",
  ASSET_UPLOAD_PHOTOS: "ASSET_UPLOAD_PHOTOS",
  ASSET_VIEW_STATS: "ASSET_VIEW_STATS",
  MY_ASSETS_VIEW: "MY_ASSETS_VIEW",

  // Meeting Room Booking
  MEETING_ROOM_ACCESS: "MEETING_ROOM_ACCESS",
  MEETING_ROOM_VIEW_CALENDAR: "MEETING_ROOM_VIEW_CALENDAR",
  MEETING_ROOM_BOOK: "MEETING_ROOM_BOOK",
  MEETING_ROOM_BOOK_FOR_OTHERS: "MEETING_ROOM_BOOK_FOR_OTHERS",
  MEETING_ROOM_CANCEL_OWN: "MEETING_ROOM_CANCEL_OWN",
  MEETING_ROOM_CANCEL_ANY: "MEETING_ROOM_CANCEL_ANY",
  MEETING_ROOM_RESCHEDULE: "MEETING_ROOM_RESCHEDULE",
  MEETING_ROOM_APPROVE: "MEETING_ROOM_APPROVE",
  MEETING_ROOM_CHECK_IN: "MEETING_ROOM_CHECK_IN",
  MEETING_ROOM_MANAGE_ROOMS: "MEETING_ROOM_MANAGE_ROOMS",
  MEETING_ROOM_MANAGE_MASTERS: "MEETING_ROOM_MANAGE_MASTERS",
  MEETING_ROOM_MANAGE_BLACKOUTS: "MEETING_ROOM_MANAGE_BLACKOUTS",
  MEETING_ROOM_MANAGE_DEVICE: "MEETING_ROOM_MANAGE_DEVICE",
  MEETING_ROOM_REPORTS_VIEW: "MEETING_ROOM_REPORTS_VIEW",
} as const;

// Permission categories
export const PERMISSION_CATEGORIES = {
  DASHBOARD: "dashboard",
  PROJECT_MANAGEMENT: "project-management",
  MASTER_DATA: "master-data",
  RBAC_SETUP: "rbac-setup",
  USER_MANAGEMENT: "user-management",
  FIELDS_FORMS: "fields-forms",
  TICKET_AUTOMATION: "ticket-automation",
  TICKET_CONFIGURATION: "ticket-configuration",
  APPROVAL_PROCESS: "approval-process",
  SLA_ESCALATION: "sla-escalation",
  KNOWLEDGE_BASE: "knowledge-base",
  INTEGRATIONS: "integrations",
  REPORTS: "reports",
  AUDIT_LOGS: "audit-logs",
  TICKETS: "tickets",
  OFFLINE_MODULE: "offline-module",
  ASSET_MANAGEMENT: "asset-management",
  SERVICE_REQUEST: "service-request",
  MEETING_ROOM: "meeting-room",
} as const;
