// Permission codes for RBAC
export const PERMISSION_CODES = {
  // Dashboard
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  DASHBOARD_VIEW_ANALYTICS: 'DASHBOARD_VIEW_ANALYTICS',
  DASHBOARD_EXPORT: 'DASHBOARD_EXPORT',

  // Project Management
  PROJECT_VIEW_ALL: 'PROJECT_VIEW_ALL',
  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_EDIT: 'PROJECT_EDIT',
  PROJECT_DELETE: 'PROJECT_DELETE',
  PROJECT_TOGGLE_STATUS: 'PROJECT_TOGGLE_STATUS',
  PROJECT_MANAGE_SETTINGS: 'PROJECT_MANAGE_SETTINGS',
  PROJECT_MANAGE_BRANDING: 'PROJECT_MANAGE_BRANDING',
  PROJECT_MANAGE_URL: 'PROJECT_MANAGE_URL',
  PROJECT_ASSIGN_USERS: 'PROJECT_ASSIGN_USERS',

  // Tickets
  TICKET_VIEW_ALL: 'TICKET_VIEW_ALL',
  TICKET_VIEW_OWN: 'TICKET_VIEW_OWN',
  TICKET_CREATE: 'TICKET_CREATE',
  TICKET_EDIT: 'TICKET_EDIT',
  TICKET_DELETE: 'TICKET_DELETE',
  TICKET_ASSIGN: 'TICKET_ASSIGN',
  TICKET_ESCALATE: 'TICKET_ESCALATE',
  TICKET_CHANGE_STATUS: 'TICKET_CHANGE_STATUS',
  TICKET_CHANGE_PRIORITY: 'TICKET_CHANGE_PRIORITY',
  TICKET_ADD_COMMENT: 'TICKET_ADD_COMMENT',
  TICKET_EDIT_COMMENT: 'TICKET_EDIT_COMMENT',
  TICKET_DELETE_COMMENT: 'TICKET_DELETE_COMMENT',
  TICKET_ADD_ATTACHMENT: 'TICKET_ADD_ATTACHMENT',
  TICKET_DELETE_ATTACHMENT: 'TICKET_DELETE_ATTACHMENT',
  TICKET_MERGE: 'TICKET_MERGE',
  TICKET_BULK_UPDATE: 'TICKET_BULK_UPDATE',
  TICKET_EXPORT: 'TICKET_EXPORT',

  // Offline Module
  OFFLINE_MODULE_ACCESS: 'OFFLINE_MODULE_ACCESS',
  OFFLINE_STUDENT_REGISTER: 'OFFLINE_STUDENT_REGISTER',
  OFFLINE_TICKET_CREATE: 'OFFLINE_TICKET_CREATE',
  OFFLINE_TICKET_RESOLVE: 'OFFLINE_TICKET_RESOLVE',
  OFFLINE_TICKET_ESCALATE: 'OFFLINE_TICKET_ESCALATE',
  OFFLINE_STUDENT_VIEW: 'OFFLINE_STUDENT_VIEW',
  OFFLINE_STUDENT_EDIT: 'OFFLINE_STUDENT_EDIT',

  // User Management
  USER_VIEW_ALL: 'USER_VIEW_ALL',
  USER_CREATE: 'USER_CREATE',
  USER_EDIT: 'USER_EDIT',
  USER_DELETE: 'USER_DELETE',
  USER_TOGGLE_STATUS: 'USER_TOGGLE_STATUS',
  USER_ASSIGN_ROLE: 'USER_ASSIGN_ROLE',
  USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',
  USER_IMPORT: 'USER_IMPORT',

  // Reports
  REPORT_VIEW_TICKETS: 'REPORT_VIEW_TICKETS',
  REPORT_VIEW_AGENT_PERFORMANCE: 'REPORT_VIEW_AGENT_PERFORMANCE',
  REPORT_VIEW_CSAT: 'REPORT_VIEW_CSAT',
  REPORT_VIEW_SLA: 'REPORT_VIEW_SLA',
  REPORT_EXPORT: 'REPORT_EXPORT',
  REPORT_CREATE_CUSTOM: 'REPORT_CREATE_CUSTOM',
  REPORT_SCHEDULE: 'REPORT_SCHEDULE',

  // Form Builder
  FORM_VIEW: 'FORM_VIEW',
  FORM_CREATE: 'FORM_CREATE',
  FORM_EDIT: 'FORM_EDIT',
  FORM_DELETE: 'FORM_DELETE',
  FORM_ASSIGN_CONTEXT: 'FORM_ASSIGN_CONTEXT',
  FORM_VIEW_AUDIT_LOGS: 'FORM_VIEW_AUDIT_LOGS',

  // Email Integration
  EMAIL_CONFIG_VIEW: 'EMAIL_CONFIG_VIEW',
  EMAIL_CONFIG_EDIT: 'EMAIL_CONFIG_EDIT',
  EMAIL_CONFIG_TEST: 'EMAIL_CONFIG_TEST',
  EMAIL_TRIGGER_MANAGE: 'EMAIL_TRIGGER_MANAGE',

  // Asset Management
  ASSET_VIEW: 'ASSET_VIEW',
  ASSET_CREATE: 'ASSET_CREATE',
  ASSET_EDIT: 'ASSET_EDIT',
  ASSET_DELETE: 'ASSET_DELETE',
  ASSET_MANAGE: 'ASSET_MANAGE',
  ASSET_MAP_TO_CENTER: 'ASSET_MAP_TO_CENTER',
  ASSET_UPLOAD_PHOTOS: 'ASSET_UPLOAD_PHOTOS',
  ASSET_VIEW_STATS: 'ASSET_VIEW_STATS',
} as const;

// Permission categories
export const PERMISSION_CATEGORIES = {
  DASHBOARD: 'dashboard',
  PROJECT_MANAGEMENT: 'project-management',
  MASTER_DATA: 'master-data',
  RBAC_SETUP: 'rbac-setup',
  USER_MANAGEMENT: 'user-management',
  FIELDS_FORMS: 'fields-forms',
  TICKET_AUTOMATION: 'ticket-automation',
  TICKET_CONFIGURATION: 'ticket-configuration',
  APPROVAL_PROCESS: 'approval-process',
  SLA_ESCALATION: 'sla-escalation',
  KNOWLEDGE_BASE: 'knowledge-base',
  INTEGRATIONS: 'integrations',
  REPORTS: 'reports',
  AUDIT_LOGS: 'audit-logs',
  TICKETS: 'tickets',
  OFFLINE_MODULE: 'offline-module',
  ASSET_MANAGEMENT: 'asset-management',
} as const;
